### ISSUE TITLE
Multiple drivers one scenario

### ISSUE THREAD

**Issue by mielas** [metacloud/molecule#1002]
# Issue Type

- Question

# Molecule and Ansible details

```
ansible --version
ansible 2.4.0.0

molecule --version
molecule, version 2.2.1

```

- Molecule installation method: pip
- Ansible installation method: OS package

# Problem

from changelog v1.11:

> Ability to declare multiple drivers in config.

but can't find any examples

> The driver’s name is specified in molecule.yml, and can be overriden on the command line. Molecule will remember the last successful driver used, and continue to use the driver for all subsequent subcommands, or until the instances are destroyed by Molecule.

so simple multiple driver: and platforms: results in duplicated key mapping. this molecule.yml won't work:

```
driver:
  name: docker
platforms:
  - name: docker-chrony
    image: centos:latest
    command: /sbin/init
    privileged: yes
driver:
  name: openstack
platforms:
  - name: openstack-chrony
    image: "CentOS-7-1708"
    flavor: 1CPU_1GB_10GB
[...]
provisioner:
  name: ansible
  playbooks:
    docker:
      create: create.yml
      destroy: destroy.yml
    openstack:
      create: create-os.yml
      destroy: destroy-os.yml
    converge: playbook.yml
```

at the same time:

> Multiple driver playbooks. In some situations a developer may choose to test the same role against different backends. Molecule will choose driver specific create/destroy playbooks, if the determined driver has a key in the playbooks section of the provisioner’s dict.

i'm looking for a way to mix multiple docker/openstack instances with some delegated instances to populate ansible molecule/<scenario>/.molecule/ansible_inventory.yml with both temporary and permanent systems
