### ISSUE TITLE
Question: Regarding group_vars path linking and overriding

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1012]
# Molecule and Ansible details
```
ansible --version
ansible 2.4.0.0

molecule --version
molecule, version 2.3.1
```
- Molecule installation method: pip
- Ansible installation method: pip

our git repo is configured as below

kerberos.yml
**group_vars**/all.yml
dev/**group_vars**/all.yml
qa/**group_vars**/all.yml
prod/**group_vars**/all.yml
roles/
        `hive`
        `hbase`
        `ruby`
molecule/default/molecule.yml  
webserver.yml
mysql.yml

i'm looking if its possible to override variables like first look in dev/group_vars , then qa/group_vars ..so on.  

currently i'm declaring all variables required in molecule.yml and am able to run it good but i want to avoid this type of declaration.

Please suggest if any improvements can be incorporated

**Comment by retr0h** [comment]
Hi @r0ckyte this is not possible.  Ansible loads group vars based on the group the system is in, and Molecule will only symlink out to a single group_vars directory.

You can try moving all of your groups under a single directory, such as:

```
group_vars/dev/all.yml
group_vars/qa/all.yml
group_vars/prod/all.yml
```
Then placing your systems into groups, but I'm not so sure how that would work.  Also, you really want to test these things in isolation a bit more.  You don't want items from dev bleeding over into your qa tests.

```
platforms:
  - name: etcd-01
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - dev
      - qa
      - prod
```

I suggest a scenario per scenario you wish to test.
