### ISSUE TITLE
provisioner.config_options.defaults.roles_path don't affecting ansible

### ISSUE THREAD

**Issue by popstas** [metacloud/molecule#1039]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.1.0
molecule 2.4.0
```

I want to test my roles without importing it with `dependency`.
In molecule v1 I done this with:
``` yaml
ansible:
  ansiblecfg_defaults:
    roles_path: "../../roles"
```

In molecule v2 I transformed it to:
``` yaml
driver:
  name: vagrant
  provider:
    name: virtualbox
...
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: /abs/path/to/roles
```

`molecule/default/.molecule/ansible.cfg` contains correct `roles_path`

This config works fine:
``` yaml
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: /abs/path/to/roles
```

`molecule --debug converge` tells that this `ansible.cfg` using, but actual roles pathes is:

- /project-parent
- /project-parent/project-root/playbook-path
- /project-parent/project-root/playbook-path/roles
- /project-parent/project-root/molecule/default/.molecule/roles
