### ISSUE TITLE
Version 2.4 and Version 2.5 results in a glob failed message

### ISSUE THREAD

**Issue by snoby** [metacloud/molecule#1051]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.1.0
molecule, version 2.4.0

```
Installed molecule from source via pip
Installed ansible via homebrew

# Desired Behaviour
Previous version when running `molecule converge` system would converge.    
 

# Actual Behaviour (Bug report only)
With new version of molecule  I'm being returned the error message:
```
[:~/work/home_servers/home-servers/roles/ethereum] master(+0/-0) ± molecule --debug converge
ERROR: 'molecule/*/molecule.yml' glob failed.  Exiting.
```

**Comment by retr0h** [comment]
This means a config file [cannot be found](https://github.com/metacloud/molecule/blob/master/molecule/command/base.py#L142).  No changes have been made to this code in some time.

**Comment by snoby** [comment]
Well I've run molecule on this role before in the past...
```
[:~/work … ervers/roles/platform] master(+0/-0) 1 ± ls
README.md     handlers/     molecule.yml  tasks/        vars/
defaults/     meta/         playbook.yml  tests/
[:~/work … ervers/roles/platform] master(+0/-0) ± molecule converge
ERROR: 'molecule/*/molecule.yml' glob failed.  Exiting.
```
here is the molecule file:
```
[:~/work … ervers/roles/platform] master(+0/-0) 1 ± cat molecule.yml
---
ansible:
  ansiblecfg_defaults:
    retry_files_enabled: False
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: zesty
      box: ubuntu/zesty64
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 2
  instances:
    - name: platform
      host_vars:
        NET_IFACE_NAME: eno1
      ansible_groups:
        - group1
verifier:
  name: testinfra
[:~/work … ervers/roles/platform] master(+0/-0) ±
```
