### ISSUE TITLE
regex support in additional_files_or_dirs:

### ISSUE THREAD

**Issue by NasrHassanein** [metacloud/molecule#1060]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible, version 2.4.2.0
molecule, version 2.5.0
```

- Molecule installation method:  pip
- Ansible installation method:  pip

# Desired Behaviour

[additional_files_or_dirs](https://molecule.readthedocs.io/en/latest/configuration.html#testinfra) is really good. I think it would be better if you added wildcard and regex support. That will enable us to include the tests inside the ansible role itself.

so it could be something like the following:
```
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../ansible-roles/test_*.py
    - ../../ansible-roles/*/tests/
```
