### ISSUE TITLE
Add custom nameserver to Docker container

### ISSUE THREAD

**Issue by asg1612** [metacloud/molecule#1095]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.4.2.0
molecule, version 2.7.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I need configure a custom nameserver into a docker container. (/etc/resolv.conf)
When I run a container manually, I insert the nameserver like this:

- sudo docker run --dns=192.168.1.100 -d nginx

How can I add the nameserver with molecule.yml file?

**Comment by dj-wasabi** [comment]
What you can do is, first updating the `create.yml` file by adding the following line:
```
dns_servers: "{{ dns_servers.links | default(omit) }}"
```
to the `Create molecule instance(s)` task.

In `molecule.yml`, you can use something like this:
```
  - name: my_host
    groups:
      - my_fancy_group
    image: milcom/centos7-systemd
    networks:
      - name: container
    dns_servers:
      - 192.168.1.100
```
When you execute a `molecule test`, the container(s) will be created with the dns option.
