### ISSUE TITLE
How to reset the Ansible connection to docker container?

### ISSUE THREAD

**Issue by bngsudheer** [metacloud/molecule#1098]
# Issue Type

- Question
- Possible limitation?

# Molecule and Ansible details

```
ansible --version: ansible 2.4.2.0
molecule --version: molecule, version 2.5.0
```

- Molecule installation method: pip
- Ansible installation method:  pip

# Desired Behaviour
I am testing a role called: ansible-role-redmine. This role depends on bngsudheer.ruby. I have my dependency like this in molecule.yml:

```
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    ignore-errors: false
```
This is my playbook.yml:

```
---
- name: Converge
  hosts: all
  roles:
    - bngsudheer.ruby
    - ansible-role-redmine
```
The problem I ran into is this: when the ansible-role-redmine starts running, it won't have access to the desired ruby version because /etc/profile.d/enableruby24.sh is not loaded into current login session. Is it possible to somehow reset the Ansible connection to docker container so that the session is forced to reset thus enabling /etc/profile.d/enableruby24.sh for the remaining tasks in the role?

I tried running source /etc/profile.d/enableruby24.sh via shell module and it didn't work.

**Comment by retr0h** [comment]
Would it work if you did?

```
---
- name: Converge
  hosts: all
  roles:
    - bngsudheer.ruby

- name: Converge
  hosts: all
  roles:
    - ansible-role-redmine
```
