### ISSUE TITLE
How can disable linting over the roles mine depends?

### ISSUE THREAD

**Issue by mdelapenya** [metacloud/molecule#1110]
# Issue Type

- Question

# Molecule and Ansible details

```
$ ansible --version
ansible 2.4.3.0
$ molecule --version
molecule, version 2.7.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I'm extending an already existing role (`geerlingguy.jenkins`), and I'm applying molecule pattern to test it. When executing `molecule test`, the lint-phase is executed and checks the first dependent role in the hierarchy. In this case, lint shows errors in the `geerlingguy.jenkins` role, which I cannot modify.

How could I skip that role? Thanks in advance

PS: I confirm that I disabled it on configuration file:

```yaml
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: instance
    image: ubuntu:16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

```

# Command Output

Executing `molecule test`:

```shell
--> Action: 'lint'
Skipping, lint is disabled.
--> Executing Flake8 on files found in ~/ansible/roles/jenkins-master/molecule/default/tests/...
Lint completed successfully.
--> Executing Ansible Lint on ~/ansible/roles/jenkins-master/molecule/default/playbook.yml...
    [ANSIBLE0006] curl used in place of get_url or uri module
   ~/ansible/roles/geerlingguy.jenkins/tasks/main.yml:35
    Task/Handler: Wait for Jenkins to start up before proceeding.

    [ANSIBLE0013] Use shell only when shell functionality is required
    ~/ansible/roles/geerlingguy.jenkins/tasks/main.yml:35
    Task/Handler: Wait for Jenkins to start up before proceeding.

...

An error occured during the test sequence.  Cleaning up
```
