### ISSUE TITLE
ERROR: Invalid lint named 'yamllint' configured.

### ISSUE THREAD

**Issue by Raffaello** [metacloud/molecule#1160]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.3
molecule 2.9.0
```

- Molecule installation method:  pip
- Ansible installation method:  pip

# Actual Behaviour (Bug report only)

my molecule config file related related:
```yml
provisioner:
  name: ansible
  options:
    vvv: True
  lint:
    name: yamllint  # <== i think is this value that has some issue
### those 2 line below commented out produce the same error
    options:
      config-file: .../../../../.yamllint
```

this config file when running `molecule test` is reporting the following error:
```
--> Action: 'lint'
ERROR: Invalid lint named 'yamllint' configured.
An error occured during the test sequence.  Cleaning up.
```

as for the documentation i should have the proper `molecule.yml` file set up. I just need to run custom lint rules on yaml or disable it. I tried also with `enabled: false` but same error happen.
ref: https://molecule.readthedocs.io/en/latest/configuration.html#yaml-lint
