### ISSUE TITLE
install/clone/copy before lint

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#1179]
Hi!

can i somehow install/clone/copy something before the lint stage? 

I would like to checkout my ansible lint rules. 

Copying them to every role feels bulky.

BTW: Cookie-cutter rocks!!! Like molecule!! Love it!

Cheers,
Alex

**Comment by retr0h** [comment]
Hey @lxhunter not currently, unless you wrapped Molecule with a shell script or something.  Incorporating this into Molecule might be tricky w/o enforcing a convention people may or may not be happy with.

Have you thought about using [gilt](http://gilt.readthedocs.org/) to manage this?  You could use gilt to check these rules into the role.  Yes, I understand its not perfect for your particular use case, so I'll think about how to solve this.

**Comment by retr0h** [comment]
> BTW: Cookie-cutter rocks!!! Like molecule!! Love it!

Oh, very glad you like this.  I think you are probably one of the only people that use cookie cutter w/ the URL option.  I thought it was a great way to manage your own templates.

**Comment by wilmardo** [comment]
You also could checkout the rules in a separate directory, set the rules dir in the config file and pass the --c flag to lint.

tree:
```
+---ansible-lint-rules
|   |   ansible-lint.yml
|   |   
|   \---rules
|           ModuleTemplateExt.py
|           RoleRelativePath.py
|           TaskNoArgs.py
```
molecule.yml
```yaml
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      c: /home/user/test/ansible-lint-rules/ansible-lint.yml
```
ansible-lint.yml:
```yaml
rulesdir:
  - rules/
use_default_rules: true
```

Not yet tested though :)
