### ISSUE TITLE
Where should I override role variables?

### ISSUE THREAD

**Issue by xoco70** [metacloud/molecule#1236]
- Question

```
ansible 2.4.2.0
molecule, version 2.12.1

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

In my role, in the default/main.yml, I have: 

```
def_proxy_env:
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
```

I tried to surcharge those values ( in molecule.yml, and prepare.yml like below), but they are never taken.

```
  environment:
    def_proxy_env:
      http_proxy: "http://xx.xx.xx.xx:8080"
      https_proxy: "http://xx.xx.xx.xx:8080"
```

Where should I surcharge those proxy values ?

**Comment by retr0h** [comment]
Not sure I understand what `supercharge` variable means.

**Comment by xoco70** [comment]
Override maybe ?

I have proxy vars set to "" in my role dictionary, but in local, I need to set them.

How should I do this ?

**Comment by rollerd** [comment]
Could you set them in molecule's `playbook.yml` file, either as `set_fact`s or extra vars?

http://docs.ansible.com/ansible/devel/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by retr0h** [comment]
You can also [set as inventory](http://molecule.readthedocs.io/en/latest/configuration.html#id12) in the provisioner.

**Comment by xoco70** [comment]
I ended up having following config:

In molecule/create.yml, I added: 

```
buildargs:
          http_proxy: "{{ lookup('env','http_proxy') }}"
          https_proxy: "{{ lookup('env','https_proxy') }}"
```
in 
```
- name: Build an Ansible compatible image
      docker_image:
        path: "{{ molecule_ephemeral_directory }}"
        name: "molecule_local/{{ item.item.image }}"
        dockerfile: "{{ item.item.dockerfile | default(item.invocation.module_args.dest) }}"
        force: "{{ item.item.force | default(true) }}"
        buildargs:
          http_proxy: "{{ lookup('env','http_proxy') }}"
          https_proxy: "{{ lookup('env','https_proxy') }}"
      with_items: "{{ platforms.results }}"
      when: platforms.changed or docker_images.results | map(attribute='images') | select('equalto', []) | list | count >= 0
```
And in molecule.yml, I had to add a group ( here group1 )

```
platforms:
  - name: instance
    image: centos:7
    groups:
      - group1
provisioner:
  name: ansible
  inventory:
    group_vars:
      group1:
        proxy_env:
          http_proxy: "{{ lookup('env','http_proxy') }}"
          https_proxy: "{{ lookup('env','https_proxy') }}"
```

**Comment by TomaszKlosinski** [comment]
I can't use playbook.yml (as it's my production playbook that I'm testing with molecule) and I can't use inventory section of molecule.yml, as I'm linking group_vars to my ansible repo group_vars). Is there any other way to override the variables?

**Comment by TomaszKlosinski** [comment]
Ok, I've found a work-around for that issue. I load testing variables only in molecule, but not in prod:
```
pre_tasks:
    - include_vars: molecule-test-variables.yml
      when: lookup('env','MOLECULE_PROJECT_DIRECTORY') != ''
```

**Comment by Lirt** [comment]
I think you want to define them in test playbook like this:

```yaml
---
- name: Install and Test my-role
  vars:
    color: blue
    http_proxy: "http://example.com"
    https_proxy: "https://example.com"
  hosts: all
  roles:
    - role: my-role
```
