### ISSUE TITLE
Allow argument flags to be passed to verfier

### ISSUE THREAD

**Issue by kunstkomputer** [metacloud/molecule#1259]
# Issue Type
- Feature request

# Molecule and Ansible details
```
ansible 2.5.0
```

```
molecule, version 2.9.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Currently arguments to the verifyer are specified as a dict and passed to the verfier as `--key=vlaue` pairs as briefly described on: https://molecule.readthedocs.io/en/latest/configuration.html#testinfra
I have a usecase where it is neccessary to just pass switch flags to the verifyer such as `-v or --setup-show` without specifying any values to be passed.
I can attempt a PR which provides the functionality if it makes sense to include such an option.

I imagine something like this but am very open to any other suggestions on the layout:
```
verifier:
  name: testinfra
  options:
    n: 1
  flags:
    - '-v'
    - '--setup-show'
```

**Comment by retr0h** [comment]
You should be using the following syntax:

```
verifier:
  name: testinfra
  options:
    n: 1
    v: True
   setup-show: True
```
