### ISSUE TITLE
port_bindings not working with docker driver

### ISSUE THREAD

**Issue by petarGitNik** [metacloud/molecule#1265]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.5.0
```

```
molecule, version 2.12.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Container created with `molecule create` or `molecule converge` should have its ports exposed (port binding).

# Actual Behaviour (Bug report only)

Even though the `port_binding` is set (as shown in my `molecule.yml` below) the `docker ps` does not show anything under PORTS.

```yaml
driver:
  name: docker
  port_bindings:
    80: 80

platforms:
  - name: instance
    image: solita/ubuntu-systemd:16.04
    privileged: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
```

Output from `docker ps`:

```
CONTAINER ID        IMAGE                                        COMMAND             CREATED             STATUS              PORTS               NAMES
1b7a382a1b67        molecule_local/solita/ubuntu-systemd:16.04   "/sbin/init"        36 seconds ago      Up 35 seconds                           instance
```

Scenario was created within an existing role as:

```
molecule init scenario --role-name test.role --scenario-name default --driver-name docker
```

How should one properly bind ports, as documentation does not seem to be clear on it? I've also tried moving `port_binding` under the `platform` tag, but the result is the same.
