### ISSUE TITLE
roles_path overwrite

### ISSUE THREAD

**Issue by freeseacher** [metacloud/molecule#1273]
Hi. i'm have such structure of my projects directory 
```
/home/shirokih % tree -L 2 -d projects 
projects
├── ansible
│   ├── ansible-role-alerta-notifications
....
├── ansible_deploy
│   ├── library
│   ├── lookup_plugins
│   ├── molecule < ---------------- here is molecule dir
│   │   ├── default
│   │   └── single
│   ├── noc_roles
│   │   ├── noc
│   │   └── web
│   ├── system_roles
│   │   ├── clickhouse
│   │   ├── grafana
│   │   ├── mongod
│   │   └── postgres
...
├── clickhouse
....
├── external
│   ├── ...
├── infrastructure
│   ├── ....
├── noc
│   ├── ....
├── postgres
....
```
and the following molecule.yml
```
...
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: /home/shirokih/projects/ansible_deploy/additional_roles:/home/shirokih/projects/ansible_deploy/system_roles:/home/shirokih/projects/ansible_deploy/noc_roles
    TOWER_SHOW_SECRETS: "True"
    ANSIBLE_STDOUT_CALLBACK: debug
    ANSIBLE_CALLBACK_WHITELIST: timer,profile_tasks
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "True"
  config_options:
    defaults:
      roles_path: ????
...
```
with default molecule roles_path i got 
```
ERROR! the role 'pre' was not found in /home/shirokih/projects/ansible_deploy/molecule/default/roles:/tmp/molecule/ansible_deploy/default/roles:/home/shirokih/projects:/home/shirokih/projects/ansible_deploy/molecule/default
```
after adding ANSIBLE_ROLES_PATH i got additional path. and it seems that playbook launches
but it fails on postgres role. 
it is in `/home/shirokih/projects/ansible_deploy/system_roles` and i have directory with same name in projects dir. 
same with each directory listed in the beginning. 
How can i overwrite roles_path to save regular project directory ?
