### ISSUE TITLE
feature request add vsphere driver to be able to create instances on vmware

### ISSUE THREAD

**Issue by mihai-satmarean** [metacloud/molecule#1276]
# Issue Type
- Feature request

# Desired Behavior
By far the best approach on testing roles.

All our configuration and testing happen on vmware VM's
We have vmware automation based on ansible modules vsphere and vmware
would it be possible to add a driver to interact directly with a vmware esxi host or vcenter server?

Thanks!

**Comment by retr0h** [comment]
I won't be able to add this since I don't have a vmware instance to test against.

**Comment by mihai-satmarean** [comment]
I could help,
But i need guidance:)

Pe 2 mai 2018, la 17:09, John Dewey <notifications@github.com> a scris:

**Comment by retr0h** [comment]
> I could help, But i need guidance:)

The problem is it needs to be maintained.  All of the drivers are tested with each release.  This would create an issue for releasing Molecule updates.  If you wish to have vmware support, you should probably use the delegated driver, and simply write your own create/destroy playbooks.

**Comment by mihai-satmarean** [comment]
This is something we can do. In fact is a very good idea.
There are some missing things, I am not sure where to take the variables from.
We have an ansible role that can creata and destroy vms already but I am not sure how to integrate it.
An working example that uses ansible playbook to create and destroy would help.
I will get started anyway.
Thanks a lot!


Pe 3 mai 2018, la 07:11, John Dewey <notifications@github.com> a scris:

**Comment by mihai-satmarean** [comment]
some direction would be appreciated here:
we have one role that works in our environment that is called infrastructure
it is a provisioner and an orchestrator, built entirely with ansible.
I am not sure how to use it in the create or destroy instances.
Below is an example on how I try using it and it is not executed as expected.
The result is that I only see some ephemeral files created but our role is not called at all.
```
molecule.yml
---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'ssh {instance} -F /tmp/ssh-config'
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: -F /path/to/ssh-config
lint:
  name: yamllint
platforms:
  - name: test-vmware-1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: delegated
verifier:
  name: testinfra
  lint:
    name: flake8

create.yml
---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  tasks:
    # Developer must implement.
    - name: "orchestrate | {{ dimension }} {{ operation }} on {{ object }}"
      include_role:
        name: infrastructure
        tasks_from: orchestrate
      vars:
        dimension: define
        object_in_scope: host
        operation_or_action: create
        profile: role-repositories
      register: server
      with_items: "{{ molecule_yml.platforms }}"
```

usually called simple from an ansible playbook, this works and we get an inventory file for the machine and triggers the vmware (if dimension has apply too) and we will have a machine running in the cluster shortly.

Thanks!
