### ISSUE TITLE
Validation for registry credentials not working as expected

### ISSUE THREAD

**Issue by vmignot** [metacloud/molecule#1297]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/Victor/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/Victor/.env/randstad/lib/python2.7/site-packages/ansible
  executable location = /Users/Victor/.env/randstad/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

```
molecule --version
molecule, version 2.11.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Since 2.11, we should be able to log in private registry, by providing credentials in molecule.yml, eg:
```
...
platforms:
  - name: validation
    image: validation:latest
    registry:
      url: private-registry:5005
      credentials:
        username: "my_username"
        password: "${MOLECULE_REGISTRY_PASSWORD}"
....
```

We should be able to provide either plain-text credentials as well as env vars.

# Actual Behaviour (Bug report only)

When using this configuration, the validation (see: https://github.com/metacloud/molecule/blob/master/molecule/model/schema_v2.py#L499-L513) will fail:

```
molecule --debug create
--> Validating schema /Users/Victor/ansible/roles/validate/molecule/default/molecule.yml.
ERROR: Failed to validate.

{'platforms': [{0: [{'registry': [{'credentials': [{'username': ["value does not match regex '^[{$]+[a-z0-9A-z]+[}]*$'"], 'password': ["value does not match regex '^[{$]+[a-z0-9A-z]+[}]*$'"]}]}]}]}]}
```

First, the regexp seems to try to force the use of env vars, which is, imo, not a desired behaviour.
Secondly, it looks like the regexp tries to validate that the _value_ of the field looks like an env vars.

I have been able to make it work by removing the regexp in the validation for the username and the password.

PS: Thank you very much for the good work :-)
