### ISSUE TITLE
Vars file for molecule

### ISSUE THREAD

**Issue by freeseacher** [metacloud/molecule#1305]
# Issue Type
- Feature request

# Desired Behavior

While developing playbook it would be nice to run molecule just with `molecule converge -s scenario name` but when launching on ci system there have to be vars defined as environment variables. 

As for now i am doing testing in two ways. 
1. default one just `git push`. and went drink tea. 
2. if first option was unsuccessful i launch `molecule create -s os`, `molecule converge -s os` and molecule login. but to get there i have to provide 
```
driver:
  name: delegated
  hostname: ${vsphere_hostname}
  esxi_hostname: ${esxi_hostname}
  username: ${vsphere_username}
  password: ${vsphere_password}
  datacenter: ${datacenter}
  validate_certs: "no"
  resource_pool: ${resource_pool}
  folder: ${folder}
```
that list of vars. of cause them are caught from env. but i have to place them anyhow :(   

the idea is to have some kind of file with answers and insert it in a such way 
`molecule create -s os --vars local.yml` or maybe have a default file. 
That file will be added to .gitignore and will never left dev laptop. 

Of cause there just can be added something like `./run.sh` with lots of exports. 
But that option looks bit ugly.
