### ISSUE TITLE
Allow dependent docker images to brought up (without testing or installing ansible on them)

### ISSUE THREAD

**Issue by cam-fulcrum** [metacloud/molecule#1317]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.5.3
```

```
molecule, version 2.14.0
```

Molecule installation method (one of):

- pipenv

Ansible installation method (one of):

- pipenv

# Desired Behavior

Hi, I'd like to be able to specify extra docker images to be brought when running molecule (similar to https://github.com/metacloud/molecule/issues/338 ). I understand we can specify extra instances under `platforms` and then only target specific instances, however by default molecule will install ansible onto every instance declared. This takes a lot of time and also could break certain containers (ie installing ansible & python on a redis docker image).

Perhaps there could be a boolean under `platforms` which specifies whether or not to build the docker image?

Thanks!

**Comment by retr0h** [comment]
> Perhaps there could be a boolean under platforms which specifies whether or not to build the docker image?

Sounds reasonable.  Could you provide a little more information about your use case?

**Comment by cam-fulcrum** [comment]
Yeah sure! So its basically an alternative to using docker-compose.

I'm using `app_role` to bring up an application service which depends on redis, I want to test that the playbook provisioning the application service works, so I need to bring up a redis container too. I don't want or need to run ansible on redis.

Currently, I have a `docker-compose.yml` in my default scenario directory
```
---
version: '3'

services:

  redis:
    image: redislabs/rejson
    ports:
      - 6379:6379
    networks:
      - app_role_molecule

networks:
  app_role_molecule:
    external: true
```

In `create.yml` I've added an extra task to bring up this network
```
    - name: Boot docker-compose dependent images
      command: docker-compose up --force-recreate -d
```
And subsequently destroying it in `destroy.yml`
```
    - name: Down docker-compose network
      command: docker-compose down
```

This works, but its a little annoying. I have to manually edit the create/destroy tasks, I have an extra docker-compose file and I have to connect the networks together.

If there was an option in platforms, I could just have the extra instances with a `build:false` flag, so they'll be brought up with the other platforms, but won't be built with them
```
platforms:
  - name: instance
    image: solita/ubuntu-systemd:latest
    command: /sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: redis
    image: redislabs/rejson
    build: false
```

Thanks so much for your help!
