### ISSUE TITLE
The ansible synchronize module is not usable from the Alpine based retr0h/molecule container

### ISSUE THREAD

**Issue by themr0c** [metacloud/molecule#1323]
# Issue Type

- Bug report

# Molecule and Ansible details

using retr0h/molecule:latest

# Desired Behavior

I wish to use the synchronize module for a task in a role, and test its behaviour using molecule container, as stated in the docker in docker video.

# Actual Behaviour (Bug report only)

Let's create an example role:

```
molecule  init role -r test_sync
```

Modify tasks/main.yml:

```
- name: synchronize
  synchronize:
    dest: /tmp/
    src: "{{ role_path }}/tasks/main.yml"
```
Then run molecule test from the retr0h/molecule:latest container:

```
docker run --rm -it -v $(pwd):/tmp/$(basename "${PWD}") -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/$(basename "${PWD}") retr0h/molecule:latest sudo molecule --debug test
```

molecule test will fail on following:

```
fatal: [instance]: FAILED! => {"changed": false, "msg": "Failed to find required executable rsync in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```

Let's circumvent limitations of current container with following molecule/default/prepare.yml:

```
---
- name: Prepare
  hosts: localhost
  gather_facts: true
  tasks:
    - name: "apk | we need rsync to use synchronize module"
      delegate_to: localhost
      apk:
        name: rsync
        state: present
        update_cache: true
      when:
        - ansible_os_family == 'Alpine'
```

Now we have another error:

```
fatal: [instance]: FAILED! => {"changed": false, "msg": "Failed to find required executable ssh in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```

Let's enhance the prepare.yml:

```
---
- name: Prepare
  hosts: localhost
  gather_facts: true
  tasks:
    - name: "apk | we need rsync and openssh to use synchronize module"
      delegate_to: localhost
      apk:
        name:
          - openssh
          - rsync
        state: present
        update_cache: true
      when:
        - ansible_os_family == 'Alpine'
```

Now we get stuck:

```
 fatal: [instance]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --blocking-io --rsh=/usr/local/bin/docker exec -i --out-format=<<CHANGED>>%i %n%L /tmp/test_sync/tasks/main.yml instance:/tmp/", "msg": "protocol version mismatch -- is your shell clean?\n(see the rsync man page for an explanation)\nrsync error: protocol incompatibility (code 2) at compat.c(178) [sender=3.1.3]\n", "rc": 2}
```
And with more debug output:

```
    TASK [test_sync : synchronize] *************************************************
    task path: /tmp/test_sync/tasks/main.yml:4
    Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/synchronize.py
    <instance> ESTABLISH LOCAL CONNECTION FOR USER: root
    <instance> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <instance> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1527598418.97-27284770950566 `" && echo ansible-tmp-1527598418.97-27284770950566="` echo /root/.ansible/tmp/ansible-tmp-1527598418.97-27284770950566 `" ) && sleep 0'
    <instance> PUT /root/.ansible/tmp/ansible-local-356Mv6Djn/tmp7gWMQv TO /root/.ansible/tmp/ansible-tmp-1527598418.97-27284770950566/synchronize.py
    <instance> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1527598418.97-27284770950566/ /root/.ansible/tmp/ansible-tmp-1527598418.97-27284770950566/synchronize.py && sleep 0'
    <instance> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1527598418.97-27284770950566/synchronize.py && sleep 0'
    The full traceback is:
      File "/tmp/ansible_r_S3vu/ansible_module_synchronize.py", line 312, in <module>
        from shlex import quote as shlex_quote
    
    fatal: [instance]: FAILED! => {
        "changed": false, 
        "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --blocking-io --rsh=/usr/local/bin/docker exec -i --out-format=<<CHANGED>>%i %n%L /tmp/test_sync/tasks/main.yml instance:/tmp/", 
        "invocation": {
            "module_args": {
                "_local_rsync_path": "rsync", 
                "_substitute_controller": false, 
                "archive": true, 
                "checksum": false, 
                "compress": true, 
                "copy_links": false, 
                "delete": false, 
                "dest": "instance:/tmp/", 
                "dest_port": null, 
                "dirs": false, 
                "existing_only": false, 
                "group": null, 
                "link_dest": null, 
                "links": null, 
                "mode": "push", 
                "owner": null, 
                "partial": false, 
                "perms": null, 
                "private_key": null, 
                "recursive": null, 
                "rsync_opts": [
                    "--blocking-io", 
                    "--rsh=/usr/local/bin/docker exec -i"
                ], 
                "rsync_path": null, 
                "rsync_timeout": 0, 
                "set_remote_user": true, 
                "src": "/tmp/test_sync/tasks/main.yml", 
                "ssh_args": null, 
                "times": null, 
                "verify_host": false
            }
        }, 
        "msg": "protocol version mismatch -- is your shell clean?\n(see the rsync man page for an explanation)\nrsync error: protocol incompatibility (code 2) at compat.c(178) [sender=3.1.3]\n", 
        "rc": 2
    }
```

I genuinely though it would be as simple as adding rsync and openssh in the Dockerfile, but apparently I am wrong. 

Now it's time to ask help :/
