### ISSUE TITLE
Cannot specify user per platform

### ISSUE THREAD

**Issue by BenWUKFast** [metacloud/molecule#1327]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

```
$ molecule --version
molecule, version 2.14.0
```

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- pip

# Desired Behavior

When running against multiple hosts you should be able to specify the user you wish to connect with for ansible. You can only specify one user for all hosts. The openstack community tends to nuke the root user by not allowing login (Or adding the key but the shell is just a script which tells you to use the correct user).

Ideal config:

```
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: CentOS 7 - Test Build
    image: "CentOS7-Alt"
    flavor: UKF2-io-2x4
    ssh_user: centos
  - name: Ubuntu 18.04 - Test Build
    image: "Ubuntu 18.04 LTS (Bionic Beaver)"
    flavor: UKF2-io-2x4
    ssh_user: ubuntu
  - name: Ubuntu Server 16.04 - Test Build
    image: "Ubuntu Server 16.04 LTS"
    flavor: UKF2-io-2x4
    ssh_user: ubuntu
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  config_options:
    defaults:
      hash_behaviour: merge
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge

    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
```

# Actual Behaviour (Bug report only)

Actual config:

```
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: CentOS 7 - Test Build
    image: "CentOS7-Alt"
    flavor: UKF2-io-2x4
  - name: Ubuntu 18.04 - Test Build
    image: "Ubuntu 18.04 LTS (Bionic Beaver)"
    flavor: UKF2-io-2x4
  - name: Ubuntu Server 16.04 - Test Build
    image: "Ubuntu Server 16.04 LTS"
    flavor: UKF2-io-2x4
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  connection_options:
    ansible_ssh_user: centos
  config_options:
    defaults:
      hash_behaviour: merge
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge

    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
```

Relevant output:

```
TASK [Install python for Ansible] **********************************************
    fatal: [Ubuntu Server 16.04 - Test Build]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '46.37.172.68' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}
    fatal: [Ubuntu 18.04 - Test Build]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '46.37.172.93' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}
    ok: [CentOS 7 - Test Build]

    PLAY RECAP *********************************************************************
    CentOS 7 - Test Build      : ok=1    changed=0    unreachable=0    failed=0
    Ubuntu 18.04 - Test Build  : ok=0    changed=0    unreachable=1    failed=0
    Ubuntu Server 16.04 - Test Build : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by BenWUKFast** [comment]
It looks like it used to be possible according to - http://molecule.readthedocs.io/en/stable-1.21/driver/#id2 - The latest documentation - https://molecule.readthedocs.io/en/latest/configuration.html#openstack - Does not include these options. I went ahead anyway and tried it but the option did not work, all 3 VM's failed this time.

**Comment by BenWUKFast** [comment]
Okay so it is possible, just a tad non obvious, possible candidate for better documentation. Will leave the issue open for the developers attention. For those googling, hopefully you see this issue and the following will be enough for you to fix your issue :)

```
platforms:
  - name: CentOS7-TestBuild
    image: "CentOS7-Alt"
    flavor: UKF2-io-2x4
  - name: Ubuntu18.04-TestBuild
    image: "Ubuntu 18.04 LTS (Bionic Beaver)"
    flavor: UKF2-io-2x4
  - name: UbuntuServer16.04-TestBuild
    image: "Ubuntu Server 16.04 LTS"
    flavor: UKF2-io-2x4
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  config_options:
    defaults:
      hash_behaviour: merge
  inventory:
    host_vars:
      CentOS7-TestBuild:
        ansible_user: centos
      Ubuntu18.04-TestBuild:
        ansible_user: ubuntu
      UbuntuServer16.04-TestBuild:
        ansible_user: ubuntu
```

**Comment by zeitounator** [comment]
In your particular use case, you can also use groups
```yaml
platforms:
  - name: CentOS7-TestBuild
    image: "CentOS7-Alt"
    flavor: UKF2-io-2x4
    groups:
      - centos
  - name: Ubuntu18.04-TestBuild
    image: "Ubuntu 18.04 LTS (Bionic Beaver)"
    flavor: UKF2-io-2x4
    groups:
      - ubuntu
  - name: UbuntuServer16.04-TestBuild
    image: "Ubuntu Server 16.04 LTS"
    flavor: UKF2-io-2x4
    groups:
      - ubuntu
provisioner:
  name: ansible
  inventory:
    group_vars:
      centos:
        ansible_user: centos
      ubuntu:
        ansible_user: ubuntu
```

**Comment by retr0h** [comment]
The openstack, gce, aws, azure molecule drivers are pretty much, do what you wish with them.  We do not have molecule.yml abstracted away super elegantly powering the create/destroy playbooks.  Mostly because, at the time the drivers were writen, only a hand full of people were actually using them.  Also, I wanted to leave these alone, b/c most everyone uses these drivers in some unique way.

You have a use case, that nobody else has ever asked about.  You also were able to solve it by updating the create playbook.  This is exactly how I expect things of this nature to go.  The create/destroy plays are yours to modify to your needs.

**Comment by BenWUKFast** [comment]
Hey @zeitounator, just wanted to let you know. I've recently got back round to this and the group_vars thing doesn't working

```
platforms:
  - name: Mol - CentOS 7
    image: "CentOS 7"
    flavor: UKF2-io-2x4
    groups:
      - centos
  - name: Mol - CentOS 6
    image: "CentOS 6"
    flavor: UKF2-io-2x4
    groups:
      - centos
  - name: Mol - Debian 8
    image: "Debian 8"
    flavor: UKF2-io-2x4
    groups:
      - debian
  - name: Mol - Debian 9
    image: "Debian 9"
    flavor: UKF2-io-2x4
    groups:
      - debian
  - name: Mol - Ubuntu 16.04
    image: "Ubuntu 16.04"
    flavor: UKF2-io-2x4
    groups:
      - ubuntu
  - name: Mol - Ubuntu 18.04
    image: "Ubuntu 18.04"
    flavor: UKF2-io-2x4
    groups:
      - ubuntu
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  config_options:
    defaults:
      hash_behaviour: merge
      display_skipped_hosts: false
  inventory:
    group_vars:
      centos:
        ansible_user: centos
      debian:
        ansible_user: debian
      ubuntu:
        ansible_user: ubuntu
```

Not exactly too hard to work around being specific about the hosts but would be nice to fix. Any ideas?

**Comment by anial-pro** [comment]
I resolved this problem with using groups, thank zeitounator BenWUKFast , plus changed variable in create.yaml


```yaml
- name: Populate instance config dict
  set_fact:
    instance_conf_dict: {
      ...
      'user': "{{ hostvars[item.instances[0].tags.instance].ansible_user }}",
      ...
  register: instance_config_dict
  when: server.changed | bool

```
