### ISSUE TITLE
Cannot create machine in Vagrant with libvirt provider

### ISSUE THREAD

**Issue by Keyhaku** [metacloud/molecule#1329]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version

ansible 2.5.4
python version = 2.7.15 (default, May  3 2018, 19:05:34) [GCC 7.3.0]
```

```
molecule --version

molecule, version 2.14.0
```

Molecule installation method :

- pip

Ansible installation method :

- pip

# Desired Behavior

I'm trying to instance an openbsd virtual machine via vagrant driver using libvirt provider.

```
molecule.yml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: instance
    box: generic/openbsd6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
```

# Actual Behaviour

The instance is not created, it seems Vagrant is trying to use VirtualBox provider altough I precise libvirt provider.

Debug Output

```
    The full traceback is:
      File "/tmp/ansible_Vu3w6F/ansible_module_molecule_vagrant.py", line 398, in up
        self._vagrant.up(provision=provision)
      File "/usr/lib/python2.7/site-packages/vagrant/__init__.py", line 337, in up
        self._call_vagrant_command(args)
      File "/usr/lib/python2.7/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
        stderr=err_fh, env=self.env)
      File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    
    failed: [localhost] (item={'box': u'generic/openbsd6', 'name': u'instance'}) => {
        "changed": false, 
        "invocation": {
            "module_args": {
                "config_options": {}, 
                "force_stop": false, 
                "instance_interfaces": [], 
                "instance_name": "instance", 
                "instance_raw_config_args": null, 
                "platform_box": "generic/openbsd6", 
                "platform_box_url": null, 
                "platform_box_version": null, 
                "provider_cpus": 2, 
                "provider_memory": 512, 
                "provider_name": "libvirt", 
                "provider_options": {}, 
                "provider_override_args": null, 
                "provider_raw_config_args": null, 
                "provision": false, 
                "state": "up"
            }
        }, 
        "item": {
            "box": "generic/openbsd6", 
            "name": "instance"
        }, 
        "msg": "ERROR: See log file '/tmp/molecule/<ROLE>/default/vagrant-instance.err'"
    }


cat /tmp/molecule/<ROLE>/default/vagrant-instance.err'

### 2018-06-06 16:09:43 ###
### 2018-06-06 16:09:43 ###
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
```

**Comment by retr0h** [comment]
Does adding the following to create.yml help per the [docs](https://molecule.readthedocs.io/en/latest/configuration.html?highlight=libvirt#molecule-vagrant-module).

```
- hosts: localhost
  connection: local
  tasks:
    - name: Create instances
      molecule_vagrant:
        instance_name: "{{ item }}"
        platform_box: ubuntu/trusty64
        provider_raw_config_args:
          - 'host = "remote-node.example.com"'
          - 'connect_via_ssh = "True"'
          - 'username = "sshuser"'
          - 'driver = "kvm"'
          - 'cpu_mode = "host-passthrough"'
        state: up
      with_items:
        - instance-1
        - instance-2
```
