### ISSUE TITLE
Variables in .env.yml get lost before provisioning tasks

### ISSUE THREAD

**Issue by ljbaar** [metacloud/molecule#1358]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.6.0
```

```
molecule 2.15.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

The variables set in .env.yml are interpolated and make their way into the platforms list.

# Actual Behaviour (Bug report only)

The `interpolated_config` when printed to stdout is correct, but when molecule tries to provision the platforms, those values are lost and all that's left are empty strings where those values should be.

Here is the tree of my project:
```
.
├── converge.yml
├── .env.yml
├── .gitignore
├── group_vars
│   └── all
│       ├── iptables.yml
│       ├── knockd.yml
│       └── openssh.yml
├── molecule
│   └── default
│       ├── Dockerfile.j2
│       ├── molecule.yml
│       ├── playbook.yml
│       └── tests
│           ├── test_default.py
│           └── test_default.pyc
├── roles
│   └── requirements.yml
└── .yamllint

```

Here is my molecule.yml

```yaml
---
dependency:
  name: galaxy
  options:
    force: false
    role-file: roles/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: js.test
    image: irs/docker-ansible/centos7:latest
    registry:
      url: redacted
    force: false
    command: /sbin/init
    privileged: true
    volumes: ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    published_ports:
      - "127.0.0.1:${js_ssh_port}:${js_ssh_port}/tcp"
      - "127.0.0.1:${js_knock_port1}:${js_knock_port1}/tcp"
      - "127.0.0.1:${js_knock_port2}:${js_knock_port2}/tcp"
      - "127.0.0.1:${js_knock_port3}:${js_knock_port3}/tcp"
provisioner:
  name: ansible
  playbooks:
    converge: "../../converge.yml"
  inventory:
    host_vars:
      js.test:
        js_ssh_port: "${js_ssh_port}"
        js_knock_port1: "${js_knock_port1}"
        js_knock_port2: "${js_knock_port2}"
        js_knock_port3: "${js_knock_port3}"
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

Here is my .env.yml
```yaml
js_ssh_port: "8022"

js_knock_port1: "15689"
js_knock_port2: "11754"
js_knock_port3: "32454"

js_iptables_rules: {}
```

The printed `interpolated_config`
```yaml
---
dependency:
  name: galaxy
  options:
    force: false
    role-file: roles/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: js.test
    image: irs/docker-ansible/centos7:latest
    registry:
      url:redacted
    force: false
    command: /sbin/init
    privileged: true
    volumes: ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    published_ports:
      - "127.0.0.1:8022:8022/tcp"
      - "127.0.0.1:15689:15689/tcp"
      - "127.0.0.1:11754:11754/tcp"
      - "127.0.0.1:32454:32454/tcp"
provisioner:
  name: ansible
  playbooks:
    converge: "../../converge.yml"
  inventory:
    host_vars:
      js.test:
        js_ssh_port: "8022"
        js_knock_port1: "15689"
        js_knock_port2: "11754"
        js_knock_port3: "32454"
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

The item in the platforms list:
```json
"item": {
                "command": "/sbin/init", 
                "force": false, 
                "image": "irs/docker-ansible/centos7:latest", 
                "name": "js.test", 
                "privileged": true, 
                "published_ports": [
                    "127.0.0.1::/tcp", 
                    "127.0.0.1::/tcp", 
                    "127.0.0.1::/tcp", 
                    "127.0.0.1::/tcp"
                ], 
                "registry": {
                    "url": "redacted"
                }, 
                "volumes": [
                    "/sys/fs/cgroup:/sys/fs/cgroup:ro"
                ]
            }, 

```
