### ISSUE TITLE
Gitlab CI pipeline example

### ISSUE THREAD

**Issue by rgarrigue** [metacloud/molecule#1362]
# Issue Type

- Feature request

# Desired Behavior

Hey. Looking for a Jenkinsfile example, I just though I could contribute with an example of my own for the doc : I'm using Gitlab CI, here's my `.gitlab-ci.yml`

```yaml
---
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

cache:
  paths:
    - .pip/
    - virtenv/

before_script:
  - pip3.6 install virtualenv
  - virtualenv virtenv
  - source virtenv/bin/activate

molecule:
  stage: test
  tags:
    - pip36
    - docker
  script:
    - docker -v
    - python -V
    - pip install ansible molecule docker
    - ansible --version
    - molecule --version
    - molecule test
```
