### ISSUE TITLE
"provider_override_args" has no effect

### ISSUE THREAD

**Issue by sveatlo** [metacloud/molecule#1385]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.6.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

```
molecule --version
molecule, version 2.16.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I am trying to generate an equivalent of this Vagrantfile
```
Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder './', '/vagrant', type: 'rsync'

  config.vm.provider :libvirt do |libvirt, override|
    libvirt.host = 'somehost'
    libvirt.username = 'jenkins'
    libvirt.connect_via_ssh = true
    override.ssh.proxy_command = "ssh somehost -l jenkins nc -N %h %p"
  end
end
```
my molecule.yml:
```
...
platforms:
  - name: instance
    box: debian/stretch64
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', type: 'rsync'"
    provider_options:
      host: '"somehost"'
      username: '"jenkins"'
      connect_via_ssh: true
    provider_override_args:
      - 'ssh.proxy_command = "ssh somehost -l jenkins nc -N %h %p"'
...
```

# Actual Behaviour (Bug report only)
the generated file `/tmp/molecule/<role-name>/default/vagrant.yml` doesn't have the `provider.override_args` filled, therefore the vagrant box never finishes starting and the `molecule test` command gets stuck
```
...
provider:
  name: libvirt
  options:
    connect_via_ssh: true
    cpus: 2
    host: '"somehost"'
    memory: 512
    username: '"jenkins"'
  override_args: null
  raw_config_args: null
```
If I change the file manually and run `vagrant up`, the box gets up and running without any problems.
```
...
- 'ssh.proxy_command = "ssh retard.moderntv.eu -l jenkins-vagrant nc -N %h %p"'
```
