### ISSUE TITLE
Python libraries and Rubocop not working in the retroh/molecule docker container

### ISSUE THREAD

**Issue by jamesla** [metacloud/molecule#1389]
I use the inspec verifier and rubocop linter. 

When trying to run molecule test through the retroh/molecule docker container it complains that rubocop is not installed. 

I tried to send a pull request for this Dockerfile myself but couldn't find where it is hosted.

Is it possible to get rubocop added to that containers image? 

```
verifier:
  name: inspec
  lint:
    name: rubocop
```
