### ISSUE TITLE
use `vagrant ssh-config` for ssh connection

### ISSUE THREAD

**Issue by sveatlo** [metacloud/molecule#1394]
# Issue Type

- Feature request

# Desired Behavior
All ssh connections (including ansible) should connect to the virtual machine using config file generated by `vagrant ssh-config` since the connection may require some specific parameters, which now have to be duplicately stated in `driver.ssh_connection_options`

**Comment by retr0h** [comment]
Can you provide an example?

**Comment by sveatlo** [comment]
I have a setup where molecule creates VMs using vagrant-libvirt on a remote system. This requires ssh option `ProxyCommand` specified. Currently I have to have it twice in the molecule.yml config file

```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  options:
    ssh_connection_options:
      -o ProxyCommand='ssh somehost -l jenkins nc -N %h %p'
lint:
  name: yamllint
platforms:
  - name: default
    box: debian/stretch64
    cpus: 4
    memory: 2048
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', type: 'rsync'"
    provider_options:
      host: '"somehost"'
      username: '"jenkins"'
      connect_via_ssh: true
      storage_pool_name: '"hdd-raid10"'
    provider_override_args:
      - 'ssh.proxy_command = "ssh somehost -l jenkins nc -N %h %p"' # this one is here because of a  bug in the vagrant's version i'm using, but a different similar command would've been there anyways implicitly
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/playbook.yml
    prepare: ../shared/prepare.yml
  config_options:
    ssh_connection:
      ssh_args: -o ProxyCommand='ssh somehost -l jenkins nc -N %h %p'
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../shared/tests/
  lint:
    name: flake8
```
I know this is very specific case probably not many people need the feature, but if molecule used same connection parameters as in `vagrant ssh-config`, you wouldn't have to worry about other weird usecases. Also figuring out where all the ssh args go takes a lot of time.
