### ISSUE TITLE
Environment variable is not defined - driver docker

### ISSUE THREAD

**Issue by Pinaute** [metacloud/molecule#1397]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.5.0
```

```
molecule, version 2.15.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I want to define an environment variable in the container

```
platforms:
  - name: debian
    image: debian:9
    environement:
      - DATA: mydata
```
# Actual Behaviour
I added a task in the playbook to test this
```
- name: Environment variable
  debug:
    msg: "Environment variable : {{ lookup('env','DATA') }}"
```

`molecule --debug test`
Below we can see that the environment variable is not defined
```
    ok: [monitoring_master] => {
        "msg": "Environment variable : "
    }
```
