### ISSUE TITLE
Change a (test) matrix via molecule.yml

### ISSUE THREAD

**Issue by rgarrigue** [metacloud/molecule#1427]
# Issue Type

- Feature request

# Molecule and Ansible details

```
molecule --version 

2.16.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I'm `ansible-galaxy install SeleniumHQ.selenium` role, which is in fact an ansible module. And one of my task is 

```
- name: Run Selenium server
  selenium:
    role: standalone
    state: running
```

Running molecule, I got the puzzling

```
Couldn't parse task at /vagrant/ansible-role-robotframework/tasks/main.yml:25 (no action detected in task. This often indicates a isspelled module name, or incorrect module path.

The error appears to have been in '<unicode string>': line 25, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

(could not open file to display line))
{ 'name': 'Install Selenium',
  'selenium': { '__file__': '/vagrant/ansible-role-robotframework/tasks/main.yml',
                '__line__': 26,
                'role': 'standalone',
                'state': 'running'}}
```

Until I understood, I've to `molecule dependency` before anything else. My immediate problem's solved, I updated my test pipeline & my doc to do that. But I'm 99% sure the next guy is gonna have the same issue trying to dev my role or another alike.

So what I'ld like to do is to keep on using `molecule test` everywhere, and define my scenario matrix in `molecule.yml` roughtly like this

```yaml
...
scenario:
  name: default
  matrix:
    test:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
...
```

I don't know if that's a feature worth the time and it's not an issue for me anymore, but maybe others will second it.

**Comment by lwm** [comment]
I am not sure I understand. You want to customise the matrix for the test sequence?  `molecule dependency` is already run under the `molecule test` sequence. Chaing the sequence is documented via https://molecule.readthedocs.io/en/latest/configuration.html#scenario.

**Comment by rgarrigue** [comment]
... Hell, this is exacty it. 

So yeah, my need is to run molecule dependency BEFORE lint, and I can do that like this

```
scenario:
  name: default
  test_sequence:
    - destroy # destroy before dependency
    - dependency # dependency need to be first since we install a module (selenium) via ansible galaxy
    - lint
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
```

Maybe there ought to be a hint about that in the molecule matrix usage / doc, this is the first thing you're looking for whenever the test matrix is wrong for your use case. In my humble opinion.

Thanks @lwm !
