### ISSUE TITLE
Execute role on target via localhost

### ISSUE THREAD

**Issue by dvianello** [metacloud/molecule#1431]
# Issue Type

- Feature request / Question

# Molecule and Ansible details

```
ansible 2.6.1
```

```
molecule, version 2.16.1.dev9
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Question

Hi there, trying to test a ansible role that requires talking to a `vault` container. 

I have the following molecule.yml:

```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: target
    image: centos/systemd
    networks:
      - name: test
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/docker.sock
    command: "/usr/sbin/init"
  - name: vault
    image: vault:0.9.6
    capabilities:
      - IPC_LOCK
    env:
      VAULT_DEV_ROOT_TOKEN_ID: the_token
    command: server -dev
    networks:
      - name: test
  - name: sidecar
    image: centos:7
    networks:
      - name: test
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  inventory:
    links:
      group_vars: ../../tests/group_vars
  env:
    VAULT_TOKEN: the_token
    VAULT_ADDR: http://localhost:8200
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

Now, as the role takes advantage of the [hashi_vault lookup](https://docs.ansible.com/ansible/2.5/plugins/lookup/hashi_vault.html) it needs to be run direcly on the `target` platform or the `lookup` would be executed on the host itself & fail, since the vault container is not accessible from the host network. Also, the role will be executed on servers against localhost in the wild, so being able to fully represent what the real life scenario is would be a plus.

Is this kind of scenario supported by molecule?

**Comment by retr0h** [comment]
I would think so.  Wouldn't your playbook.yml have a host block targeting the `target` container, and the `hashi_vault lookup` would execute against that host?

**Comment by dvianello** [comment]
Hi!

Yes, my `playbook.yml` look like this:
```
---
- name: Converge
  hosts: target
  roles:
    - role: ansible-service-configurator
```
However, `lookups` are executed on the host where ansible is running, not on the target machine. This means that `hashi_vault` is executed on the host, which doesn't have any way to get to vault that is isolated withing the docker network. 

What (I believe) I would need is molecule copying role and playbook over to the target docker container, and execute ansible there with `localhost` as a target. 

Or am I missing something? If that's the case, apologies in advance!
