### ISSUE TITLE
Why does docker create.yml command default to sleep ? 

### ISSUE THREAD

**Issue by rgarrigue** [metacloud/molecule#1441]
Hi

I'm wondering why the command in the default `create.yml` below default to this sleep loop ? Shouldn't this specific left to the original Docker image ? 

```yaml
...
    - name: Create molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        docker_host: "{{ item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        hostname: "{{ item.hostname | default(item.name) }}"
        image: "molecule_local/{{ item.image }}"
        state: started
        recreate: false
        log_driver: json-file
        command: "{{ item.command | default('bash -c \"while true; do sleep 10000; done\"') }}"
        privileged: "{{ item.privileged | default(omit) }}"
        security_opts: "{{ item.security_opts | default(omit) }}"
...
```

I'm asking because I find this counter-intuitive. I know the "specify command: /.../init for systemd container" is documented, but working with molecule for some times I don't read the doc as often as before... and I ended up searching a couple of hour before realizing this is why my services were broken.
