### ISSUE TITLE
says instances already prepared and skips for no reason

### ISSUE THREAD

**Issue by Dmitry1987** [metacloud/molecule#1459]
# Issue Type
- Bug report

# Molecule and Ansible details

```
ansible --version
2.6.3

```

```
molecule --version
2.17.0
```

Molecule installation method:
- pip

Ansible installation method:
- pip

# Desired Behavior

"prepare.yml" needs to play

# Actual Behaviour (Bug report only)

Skips the prepare step for no obvious reason   

The molecule.yml is
```
---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: molecule-ansible-base
    image: ami-7e21a11a
    instance_type: t2.micro
    vpc_subnet_id: subnet-xxxxxxx
    security_group_name: default
provisioner:
  name: ansible
  log: True
  options:
    e: ansible_python_interpreter=/usr/bin/python3
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: playbook.yml
    destroy: destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - syntax
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8

```

the ec2 machine created by create.yml works ok,
the prepare.yml has a simple palybook for python install and some stuff:

```
---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-zipstream)
      become: true
      changed_when: false
    - name: Install required packages
      apt:
        pkg: "{{item}}"
        update_cache: yes
        state: present
      with_items:
        - python3-pip
        - python3
        - awscli
    - name: Install pip3 packages
      pip:
        name: "{{ item }}"
        executable: pip3
      with_items:
        - kmod
```

What I see in debug mode:

![image](https://user-images.githubusercontent.com/9369080/44828110-2f97fa00-abcb-11e8-8466-bd6b38897e6c.png)

I don't understand why it decides "instances already prepared" when they're not 😄
