### ISSUE TITLE
Question: running commands on multiple instances

### ISSUE THREAD

**Issue by tjanez** [metacloud/molecule#146]
Hi!

When I'm developing Ansible roles I usually target multiple operating systems or multiple versions of a single operating system.

Let's say I have `molecule.yml` which has the following `vagrant` section:
```yaml
vagrant:
  raw_config_args:
    - "ssh.insert_key = false"

  platforms:
    - name: centos7
      box: centos/7
    - name: fedora23
      box: fedora/23-cloud-base
      # Install Python 2 and dependencies
      # NOTE: This is a work-around to make Ansible work with the Fedora 23's
      # official Vagrant box which doesn't include Python 2
      triggers:
        - trigger: after
          action: up
          cmd: run_remote 'dnf install -y python2 python2-dnf libselinux-python'

  providers:
    - name: virtualbox
      type: virtualbox

  instances:
    - name: test
      ansible_groups:
        - molecule
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
```

How can I work with multiple supported platforms (namely, `centos7` and `fedora23`)?
- Do I define multiple instances, one for each supported platform? How can I specify which platform an instance uses in instance's definition in `molecule.yml`?
- Can I specify a parameter to molecule commands that will tell Molecule to iterate through all supported platforms? Is it possible to specify a setting to pass this parameter to molecule commands by default?
