### ISSUE TITLE
ansible.cfg custom ssh key ignored

### ISSUE THREAD

**Issue by Dmitry1987** [metacloud/molecule#1460]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
2.6.3
```

```
molecule --version
2.17.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Use the private key that was specified in config file, for playbooks of "prepare.yml" and "converge.yml", if the key exists, and has valid permissions (both folder and key, the folder is 0700 and file is 0600, key works in manual verification).

# Actual Behaviour (Bug report only)

Attempts to either use some default key found in molecule container or just ignores the key/user setting, I don't know, but it says can't connect if I try to use a custom SSH private key (downloaded from S3 during molecule create stage).  If I use the auto-generated ssh key it works though.  I don't understand why "ansible.cfg" is ignored (I put it in same folder with molecule.yml and other files).

It has this 
```
[defaults]
host_key_checking = False
timeout = 50
remote_user = ubuntu
private_key_file = /ssh/ssh_key
```

folder "/ssh" is chmod 700
file is 600.  it should work.  Will be glad for any advice 😄

**Comment by Dmitry1987** [comment]
![image](https://user-images.githubusercontent.com/9369080/44828558-59eab700-abcd-11e8-9dd0-a577f43ea2a7.png)


It shows the location of ansible.cfg file properly, it's the location of all molecule files in the role that's being tested... why would it ignore the ssh key location or username?   because if it will use what specified - it will work

**Comment by Dmitry1987** [comment]
I printed the "inventory" file that molecule creates (printed it right in "create.yml" step with a file read option... had to use "slurp" module for proper visual candy I guess :)  but whatever)

![image](https://user-images.githubusercontent.com/9369080/44829818-6c67ef00-abd3-11e8-9972-d3eac8f82594.png)


How does it know where to look for IP address, key, username?

**Comment by Dmitry1987** [comment]
i found out when i used 'auto generated' ssh key (from some molecule example i found) 
the inventory file looked like this
```
cat /var/folders/q8/z0fxhmvx33b07bxb15php39wx3w1vp/T/molecule/ansible-vpn-base/default/ansible_inventory.yml
# Molecule managed

---
all:
  hosts:
    molecule: &id001
      ansible_host: xx.xx.xx.xx
      ansible_port: 22
      ansible_private_key_file: /var/folders/q8/z0fxhmvx33b07bxb15php39wx3w1vp/T/molecule/ansible-vpn-base/default/ssh_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: ubuntu
      connection: ssh
  vars:
    molecule_ephemeral_directory: '{{ lookup(''env'', ''MOLECULE_EPHEMERAL_DIRECTORY'')
      }}'
    molecule_file: '{{ lookup(''env'', ''MOLECULE_FILE'') }}'
    molecule_instance_config: '{{ lookup(''env'', ''MOLECULE_INSTANCE_CONFIG'') }}'
    molecule_scenario_directory: '{{ lookup(''env'', ''MOLECULE_SCENARIO_DIRECTORY'')
      }}'
    molecule_yml: '{{ lookup(''file'', molecule_file) | molecule_from_yaml }}'
ungrouped:
  hosts:
    molecule: *id001
  vars: {}
```

and now it looks like above screenshot :(
