### ISSUE TITLE
molecule-driver-contrib: community managed drivers

### ISSUE THREAD

**Issue by lwm** [metacloud/molecule#1479]
Regarding https://github.com/metacloud/molecule/pull/1473#issuecomment-421832966.

> Hi @bandit145, I am hesitant to commit drivers which rely on community members maintaining drivers which most people do not use. To be honest, I think we already have too many drivers. Most people simply use Vagrant and Docker. Very few people use the others, and I don't actively test the others.

And since I am working on https://github.com/metacloud/molecule/pull/1458, I am of course interested in this.

So, have you given any thought to a `molecule-driver-contrib` which is pluggable from the end-user side and introduces no maintenance burden on you all here? We could say that those drivers are maintained by the community and those community members are responsible for them. No guarantees are given back in molecule core. That would steer all the maintenance tickets away from here.

I would guess core devs here would know the best way that is possible, if this is feasible.

I'd be happy to QA test any effort here in plugging in my Linode driver functionality.

**Comment by lwm** [comment]
> If just the tickets get issued to the correct maintainer that should fix most of the problems (I think open for discussion of course). When a maintainer seems inactive over a longer period of time the driver should be removed from Molecule core.

I am not sure if you are aware, but this is basically what is already happening. This ticket is about talking about other potential solutions because it seems this is not working for core devs (this may not be the case entirely but from the original motivating comment, I want to start this discussion in case that is so).

> Another thing to consider is a contrib is a real stretch without a publicly visible CI. The community maintainers then must test all the changes locally, this takes a real time effort.

Each community driver maintains its own CI. This CI consists of: `molecule init role -r foobar -d <community-driver> && cd foobar && molecule test`. That's it, right? If the thing passes, the community driver is still working.

**Comment by bandit145** [comment]
Maybe an option would be to handle drivers like Ansible handles module discovery. As an example you could have a custom driver in a "drivers" folder in the cwd and molecule could pick that up and could use the driver(s) in that directory.

**Comment by retr0h** [comment]
So you can more or less do this today with the 'delegated' driver.  The delegated driver defaults to `managed: true`, which means as the developer you bring your own create/destroy playbooks and conform to the `instance_config` API in create.yml.

We have had users already use this for a vmware driver.  Community members simply drop in 3rd party drivers, and set the driver to delegated, and you should be good to go.

**Comment by wilmardo** [comment]
Is it a possibility to do something like Ansible does with for example Azure (ansible[azure)]? 
`pip install molecule` for Molecule with Docker and Vagrant
 `pip install molecule[coomunity_driver_name]` and move these community drivers into a specific directory in the repo.

**Comment by lwm** [comment]
> So you can more or less do this today with the 'delegated' driver. The delegated driver defaults to managed: true, which means as the developer you bring your own create/destroy playbooks and conform to the instance_config API in create.yml. We have had users already use this for a vmware driver. Community members simply drop in 3rd party provisioning playbooks, and set the driver to delegated, and you should be good to go.

You know, I'd be down to just do this and leave it at that. However, there is one thing this doesn't cover, I think. In my Linode PR, I had to add an actual driver python module (see https://github.com/metacloud/molecule/pull/1458/files#diff-f31994c777cf7153ef405f9b02ab920a) which did some fiddling with the SSH password and instance name for connection details. This is not covered by the `delegated` method, right?

**Comment by bandit145** [comment]
@lwm I believe you can set those bits in the delegated declaration (molecule.yml). I did consider using the delegated driver for mine originally but since my use case is company wide I thought it would be nicer to have it all in the main project if possible.

**Comment by watsonb** [comment]
I like the spirit of this discussion and can see both sides of the coin.  We've got a boat load of Ansible roles and try very hard to leverage molecule for role development and automated CI with Jenkins.  We're a mixed Linux/Windows shop and have to support both platforms.  And, to make matters worse, we're a hybrid cloud shop using Azure and on-prem VMWare.

To date, I've leveraged the delegated driver and we can spin molecule instances up/down on-prem in VMWare when we write/test roles that don't play well with Docker.  The downside of this is that each role has these drivers in them and keeping consistency across the growing number of roles we have is a royal pain.  Something pluggable would be cool, but I see how it could be difficult to support a wide variety of use cases.  I've had success adapting the delegated driver to spin up/down VMs in Azure as well.

My most difficult pain point at the moment is supporting Windows.  I've got some Jenkins slaves with Virtualbox/Vagrant on them and built a Windows image with Packer, but the molecule vagrant driver with these Windows vbox images and the winrm stuff just isn't reliable enough.  And then there's the whole verification piece that can be messy and without being able to RDP or access the Windows GUI it can be tough to visually check this stuff as well.

I think I'd like to try the delegated driver spinning up Windows VMs in VMWare (or even Azure), but I can't figure out how to coerce Molecule to retain/use Ansible/WinRM stuff to connect to these things for converge/verify steps after they've been created (the create/destroy is the easy part).  Essentially I need to adapt the following to store the WinRM bits, but I have no idea how to make Molecule make use of it once it is stored:

```yaml
- name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.instance.hw_name }}",
          'address': "{{ item.instance.ipv4 }}",
          'user': "{{ molecule_yml.driver.ssh_user }}",
          'port': "{{ molecule_yml.driver.ssh_port }}",
          'identity_file': "{{ molecule_yml.driver.ssh_identity_file }}"
        }
      with_items: "{{ server.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        # NOTE(retr0h): Workaround for Ansible 2.2.
        #               https://github.com/ansible/ansible/issues/20885
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool

    - name: render ssh_config for instances
      template:
        src: 'ssh_config.j2'
        dest: "/tmp/molecule-ssh-config"
      when: server.changed | bool
```
Once created, I'd like to be able to `molecule converge` and `molecule verify` on these Windows-based VMs.  As a bonus I could use native VMWare/Azure methods to get access to the GUI for manual/visual inspection.

I feel like I'm close between my experiments with Vagrant and the delegated driver, but I can seem to put them together into something reliable.

**Comment by lwm** [comment]
> but I can't figure out how to coerce Molecule to retain/use Ansible/WinRM stuff to connect to these things for converge/verify steps after they've been created (the create/destroy is the easy part). ... but I have no idea how to make Molecule make use of it once it is stored

I think this is the same point as https://github.com/metacloud/molecule/issues/1479#issuecomment-422468287?

If we could extend the delegated driver concept to allow for a driver python module as well, then it would be more useful. However, this still doesn't get away from the pain point that when you have 100+ roles and you 'eject' your delegated driver plays into them and then you want to make a change to them all ...

https://github.com/metacloud/molecule/issues/1479#issuecomment-422285162 is interesting!

**Comment by watsonb** [comment]
Here is the output of my latest attempt.

First the pre-conditions going in (molecule config):

```yaml
# Example of VMWare VMs spun up with sizing/template info
platforms:
  - name: ubuntu-1604-ar-hippocampe-$BRANCH_NAME
    template: 'ubuntu-1604-server-02'
    disk_size: 30
    memory_mb: 1048
    num_cpus: 1
    groups:
      - ubuntu
      - hippocampe
      - nodejs
  - name: centos-7-ar-hippocampe-$BRANCH_NAME
    template: 'centos-7-server-01'
    disk_size: 30
    memory_mb: 1048
    num_cpus: 1
    groups:
      - centos
      - hippocampe
      - nodejs
provisioner:
  name: ansible
  inventory:
    group_vars:
      ubuntu:
        shell_profiles:
          - .profile
      centos:
        shell_profiles:
          - .bash_profile
      nodejs:
        install_nvm_deps: true
        nvm_symlink_dir: /usr/local/bin
        nvm_version: v0.33.11
        nodejs_clean_install: true
        node_version: 10.10.0
        node_versions:
          - 8.12.0
        node_packages:
          - bower
```
The prepare playbook that applies the role:
```yaml
- name: Prepare
  hosts: all
  gather_facts: true
  # become: true
  # become_user: root
  pre_tasks:

    - name: LINEINFILE | Give ssh user passwordless sudo
      become: true
      become_user: root
      lineinfile:
        create: true
        group: root
        owner: root
        mode: 'u=r,g=,o='
        path: "/etc/sudoers.d/{{ molecule_yml.driver.ssh_user }}"
        line: "{{ molecule_yml.driver.ssh_user }}     ALL=(ALL)   NOPASSWD: ALL"
        state: present

  roles:
    # - role: ar_nodejs
    - role: fubarhouse.nodejs
```

Shell output:

```bash
(venv_ansible-2.5.2) bw.admin@knebawils002:/workspace/vsts/ansible/roles/ar_hippocampe$ molecule dependency
--> Validating schema /workspace/vsts/ansible/roles/ar_hippocampe/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    └── dependency
    
--> Scenario: 'default'
--> Action: 'dependency'
    - changing role ar_nodejs from v0.2.0 to v0.2.0
    - extracting ar_nodejs to /workspace/vsts/ansible/roles/ar_hippocampe/molecule/default/roles/ar_nodejs
    - ar_nodejs (v0.2.0) was installed successfully
    - changing role config_encoder_filters from  to unspecified
    - extracting config_encoder_filters to /workspace/vsts/ansible/roles/ar_hippocampe/molecule/default/roles/config_encoder_filters
    - config_encoder_filters was installed successfully
    - changing role fubarhouse.nodejs from issue-76 to issue-76
    - extracting fubarhouse.nodejs to /workspace/vsts/ansible/roles/ar_hippocampe/molecule/default/roles/fubarhouse.nodejs
    - fubarhouse.nodejs (issue-76) was installed successfully
Dependency completed successfully.
(venv_ansible-2.5.2) bw.admin@knebawils002:/workspace/vsts/ansible/roles/ar_hippocampe$ molecule create
--> Validating schema /workspace/vsts/ansible/roles/ar_hippocampe/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── create
    └── prepare
    
--> Scenario: 'default'
--> Action: 'create'
    
    PLAY [Create] ******************************************************************
    
    TASK [VMWARE_GUEST | Ensure VMs exist in VMware] *******************************
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    TASK [Populate instance config dict] *******************************************
    ok: [localhost] => (item=None)
    ok: [localhost] => (item=None)
    
    TASK [Convert instance config dict to a list] **********************************
    ok: [localhost]
    
    TASK [Dump instance config] ****************************************************
    changed: [localhost]
    
    TASK [render ssh_config for instances] *****************************************
    changed: [localhost]
    
    TASK [Wait for system to become reachable] *************************************
    ok: [localhost] => (item=None)
    ok: [localhost] => (item=None)
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=6    changed=3    unreachable=0    failed=0
    
    
--> Scenario: 'default'
--> Action: 'prepare'
    
    PLAY [Prepare] *****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [ubuntu-1604-ar-hippocampe-benlocal]
    ok: [centos-7-ar-hippocampe-benlocal]
    
    TASK [LINEINFILE | Give ssh user passwordless sudo] ****************************
    changed: [ubuntu-1604-ar-hippocampe-benlocal]
    changed: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : include_tasks] ***************************************
    included: /workspace/vsts/ansible/roles/ar_hippocampe/molecule/default/roles/fubarhouse.nodejs/tasks/setup.yml for ubuntu-1604-ar-hippocampe-benlocal, centos-7-ar-hippocampe-benlocal
    
    TASK [fubarhouse.nodejs : NodeJS | Install dependencies (CentOS)] **************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal] => (item=[]) 
    changed: [centos-7-ar-hippocampe-benlocal] => (item=[u'curl', u'gcc', u'git', u'findutils', u'make', u'rsync', u'tar'])
    
    TASK [fubarhouse.nodejs : NodeJS | Install dependencies (Debian)] **************
    skipping: [centos-7-ar-hippocampe-benlocal] => (item=[]) 
changed: [ubuntu-1604-ar-hippocampe-benlocal] => (item=[u'curl', u'gcc', u'git', u'findutils', u'make', u'rsync', u'tar'])
[DEPRECATION WARNING]: State 'installed' is deprecated. Using state 'present'
instead.. This feature will be removed in version 2.9. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.
    
    TASK [fubarhouse.nodejs : NodeJS | Install dependencies (RedHat)] **************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal] => (item=[]) 
    skipping: [centos-7-ar-hippocampe-benlocal] => (item=[]) 
    
    TASK [fubarhouse.nodejs : Set default ivm installation directory] **************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : Set default nvm installation directory] **************
    ok: [ubuntu-1604-ar-hippocampe-benlocal]
    ok: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : include_tasks] ***************************************
    included: /workspace/vsts/ansible/roles/ar_hippocampe/molecule/default/roles/fubarhouse.nodejs/tasks/nvm.yml for ubuntu-1604-ar-hippocampe-benlocal, centos-7-ar-hippocampe-benlocal
    
    TASK [fubarhouse.nodejs : NVM | Looking at shell profiles] *********************
    ok: [ubuntu-1604-ar-hippocampe-benlocal] => (item=.profile)
    ok: [centos-7-ar-hippocampe-benlocal] => (item=.bash_profile)
    
    TASK [fubarhouse.nodejs : NVM | Clean-up] **************************************
    ok: [ubuntu-1604-ar-hippocampe-benlocal]
    ok: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Clean-up default version from shell profiles] ***
    ok: [ubuntu-1604-ar-hippocampe-benlocal] => (item={'_ansible_parsed': True, u'stat': {u'isuid': False, u'uid': 1000, u'exists': True, u'attr_flags': u'e', u'woth': False, u'isreg': True, u'device_type': 0, u'mtime': 1494938978.0, u'block_size': 4096, u'inode': 523300, u'isgid': False, u'size': 655, u'executable': False, u'roth': True, u'charset': u'us-ascii', u'readable': True, u'version': u'18446744072056662227', u'pw_name': u'ansible', u'gid': 1000, u'ischr': False, u'wusr': True, u'writeable': True, u'isdir': False, u'blocks': 8, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'gr_name': u'ansible', u'path': u'.profile', u'xusr': False, u'atime': 1531775255.2080011, u'mimetype': u'text/plain', u'ctime': 1524504892.2734447, u'isblk': False, u'xgrp': False, u'dev': 64512, u'wgrp': False, u'isfifo': False, u'mode': u'0644', u'checksum': u'dded66a8a7137b974a4f57a4ec378eda51fbcae6', u'islnk': False, u'attributes': [u'extents']}, u'changed': False, '_ansible_no_log': False, 'item': u'.profile', '_ansible_item_result': True, 'failed': False, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.profile', u'get_md5': None, u'get_mime': True, u'get_attributes': True}}, '_ansible_ignore_errors': None})
    ok: [centos-7-ar-hippocampe-benlocal] => (item={'_ansible_parsed': True, u'stat': {u'isuid': False, u'uid': 1001, u'exists': True, u'attr_flags': u'', u'woth': False, u'isreg': True, u'device_type': 0, u'mtime': 1523407981.0, u'block_size': 4096, u'inode': 33582193, u'isgid': False, u'size': 193, u'executable': False, u'roth': True, u'charset': u'us-ascii', u'readable': True, u'version': u'18446744073125667890', u'pw_name': u'ansible', u'gid': 1001, u'ischr': False, u'wusr': True, u'writeable': True, u'isdir': False, u'blocks': 8, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'gr_name': u'ansible', u'path': u'.bash_profile', u'xusr': False, u'atime': 1532397599.7463272, u'mimetype': u'text/plain', u'ctime': 1528463254.065362, u'isblk': False, u'xgrp': False, u'dev': 64768, u'wgrp': False, u'isfifo': False, u'mode': u'0644', u'checksum': u'82a36c2c2e245f5416ca253fb38ff3346d6e8d7e', u'islnk': False, u'attributes': []}, u'changed': False, '_ansible_no_log': False, 'item': u'.bash_profile', '_ansible_item_result': True, 'failed': False, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.bash_profile', u'get_md5': None, u'get_mime': True, u'get_attributes': True}}, '_ansible_ignore_errors': None})
    
    TASK [fubarhouse.nodejs : NVM | Clean-up other versions from shell profiles] ***
    ok: [ubuntu-1604-ar-hippocampe-benlocal] => (item=[{'_ansible_parsed': True, u'stat': {u'isuid': False, u'uid': 1000, u'exists': True, u'attr_flags': u'e', u'woth': False, u'isreg': True, u'device_type': 0, u'mtime': 1494938978.0, u'block_size': 4096, u'inode': 523300, u'isgid': False, u'size': 655, u'wgrp': False, u'executable': False, u'charset': u'us-ascii', u'readable': True, u'version': u'18446744072056662227', u'pw_name': u'ansible', u'gid': 1000, u'ischr': False, u'wusr': True, u'writeable': True, u'mimetype': u'text/plain', u'blocks': 8, u'xoth': False, u'islnk': False, u'nlink': 1, u'issock': False, u'rgrp': True, u'gr_name': u'ansible', u'path': u'.profile', u'xusr': False, u'atime': 1531775255.2080011, u'isdir': False, u'ctime': 1524504892.2734447, u'isblk': False, u'xgrp': False, u'dev': 64512, u'roth': True, u'isfifo': False, u'mode': u'0644', u'checksum': u'dded66a8a7137b974a4f57a4ec378eda51fbcae6', u'rusr': True, u'attributes': [u'extents']}, '_ansible_item_result': True, '_ansible_no_log': False, 'failed': False, u'changed': False, 'item': u'.profile', u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.profile', u'get_md5': None, u'get_mime': True, u'get_attributes': True}}, '_ansible_ignore_errors': None}, u'8.12.0'])
    ok: [centos-7-ar-hippocampe-benlocal] => (item=[{'_ansible_parsed': True, u'stat': {u'isuid': False, u'uid': 1001, u'exists': True, u'attr_flags': u'', u'woth': False, u'isreg': True, u'device_type': 0, u'mtime': 1523407981.0, u'block_size': 4096, u'inode': 33582193, u'isgid': False, u'size': 193, u'wgrp': False, u'executable': False, u'charset': u'us-ascii', u'readable': True, u'version': u'18446744073125667890', u'pw_name': u'ansible', u'gid': 1001, u'ischr': False, u'wusr': True, u'writeable': True, u'mimetype': u'text/plain', u'blocks': 8, u'xoth': False, u'islnk': False, u'nlink': 1, u'issock': False, u'rgrp': True, u'gr_name': u'ansible', u'path': u'.bash_profile', u'xusr': False, u'atime': 1532397599.7463272, u'isdir': False, u'ctime': 1528463254.065362, u'isblk': False, u'xgrp': False, u'dev': 64768, u'roth': True, u'isfifo': False, u'mode': u'0644', u'checksum': u'82a36c2c2e245f5416ca253fb38ff3346d6e8d7e', u'rusr': True, u'attributes': []}, '_ansible_item_result': True, '_ansible_no_log': False, 'failed': False, u'changed': False, 'item': u'.bash_profile', u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'.bash_profile', u'get_md5': None, u'get_mime': True, u'get_attributes': True}}, '_ansible_ignore_errors': None}, u'8.12.0'])
    
    TASK [fubarhouse.nodejs : NodeJS | Remove imported exports not associated to specific versions] ***
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Check] *****************************************
    ok: [ubuntu-1604-ar-hippocampe-benlocal]
    ok: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Get distribution] ******************************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Create temporary extraction directory] *********
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Create pernament extraction directory] *********
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Unpack distribution] ***************************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Moving to installation directory] **************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Moving to installation directory] **************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal]
    skipping: [centos-7-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Remove temporary data] *************************
    skipping: [ubuntu-1604-ar-hippocampe-benlocal] => (item=/tmp/v0.33.11.tar.gz) 
    skipping: [ubuntu-1604-ar-hippocampe-benlocal] => (item=/tmp/nvm-v0.33.11) 
    skipping: [centos-7-ar-hippocampe-benlocal] => (item=/tmp/v0.33.11.tar.gz) 
    skipping: [centos-7-ar-hippocampe-benlocal] => (item=/tmp/nvm-v0.33.11) 
    
    TASK [fubarhouse.nodejs : NVM | Clone] *****************************************
    changed: [centos-7-ar-hippocampe-benlocal]
    changed: [ubuntu-1604-ar-hippocampe-benlocal]
    
    TASK [fubarhouse.nodejs : NVM | Install] ***************************************
    changed: [ubuntu-1604-ar-hippocampe-benlocal]
    fatal: [centos-7-ar-hippocampe-benlocal]: FAILED! => {"changed": true, "cmd": "~/.nvm/install.sh", "delta": "0:00:00.574416", "end": "2018-09-19 16:30:53.438248", "msg": "non-zero return code", "rc": 1, "start": "2018-09-19 16:30:52.863832", "stderr": "Failed to update nvm, run 'git fetch' in /home/ansible/.nvm yourself.", "stderr_lines": ["Failed to update nvm, run 'git fetch' in /home/ansible/.nvm yourself."], "stdout": "=> nvm is already installed in /home/ansible/.nvm, trying to update using git\n\r=> ", "stdout_lines": ["=> nvm is already installed in /home/ansible/.nvm, trying to update using git", "", "=> "]}
    
    TASK [fubarhouse.nodejs : NVM | Create an executable] **************************
    fatal: [ubuntu-1604-ar-hippocampe-benlocal]: FAILED! => {"changed": false, "checksum": "e0a51eb58a55439220e5563058b8aece0dd91d76", "msg": "Destination /usr/local/bin not writable"}
    
    PLAY RECAP *********************************************************************
    centos-7-ar-hippocampe-benlocal : ok=12   changed=3    unreachable=0    failed=1   
    ubuntu-1604-ar-hippocampe-benlocal : ok=13   changed=4    unreachable=0    failed=1 
```

It looks like my CentOS instance needs that `git fetch` fix you proposed in another issue.  Should I specify another location other than `/usr/local/bin` if I'm running this without `become: true`.  As you can see in my prepare playbook, I explicitly commented out `become: true` and `become_user: root` so the playbook itself would run unprivileged but individual tasks that require it can escalate if needed.  You can see that the user I'm running as was able to install package dependencies as indicated by `install_nvm_deps: true` and getting past those tasks.
