### ISSUE TITLE
Registry credentials does not match regex

### ISSUE THREAD

**Issue by jamesla** [metacloud/molecule#1494]
# Issue Type

- Bug report

# Molecule and Ansible details

```
2.6.4
```

```
2.18.1
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

molecule test should run tests

# Actual Behaviour (Bug report only)

This appears to have been reported and resolved before however it is still occuring. Currently not possible to use a docker registry with authentication.

# Steps to reproduce
1. Add the following to your molecule.yml
```
platforms:
  - name: centos
    registry:
      url: test.test.com
      credentials:
        username: TEST123
        password: TEST123
```
2. Run molecule test
```
{'platforms': [{0: [{'registry': [{'credentials': [{'password': ["value does not match regex '^[{$]+[a-z0-9A-Z]+[}]*$'"]}]}]}]}]}
```
