### ISSUE TITLE
The vagrant not support static ip assignment 

### ISSUE THREAD

**Issue by TieWei** [metacloud/molecule#155]
Although currently the network type could be set as static, but there's no ip parameter could be set, it end with below error.
```
(venv)wtie@cisco.pxe_server$ molecule converge  --platform=rhel-7
Bringing machine 'pxe-server-01-rhel-7' up with 'virtualbox' provider...
Bringing machine 'pxe-client-01-rhel-7' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:
vm:
* An IP is required for a private network.

```
In molecule.yml
```
    - name: pxe-server-01
      ansible_groups:
        - aio
        - pxe_server
      interfaces:
        - network_name: private_network
          type: static
          ip: 192.168.11.3
          auto_config: true
```
