### ISSUE TITLE
Does test always need to destroy machine after a full run?

### ISSUE THREAD

**Issue by techraf** [metacloud/molecule#188]
If I define my test sequence in `Molecule.yml` like this:

```
molecule:
  test:
    sequence:
      - destroy
      - create
      - converge
      - idempotence
      - verify
#      - destroy
```

my expectation is that the machine will remain up. It doesn't.

Shouldn't the logic be: if user specified `test:` they should be considered in full control (and thus Molecule should expect explicit `destroy` at the end instead of inferring one)?
