### ISSUE TITLE
Update molecule's config syntax to be more like test kitchen

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#204]
This is a fairly tough job to merge into molecule, however, the config would benefit from following the test kitchen "syntax".  Especially b/c testing various scenarios would be beneficial.  I have started to [prototype](https://github.com/retr0h/maquina/blob/master/tests/conftest.py#L68-L95) this.

This would bump molecule to 2.x as part of the change.

**Comment by kireledan** [comment]
Im a huge fan of this. 👍 👍 👍

**Comment by dhutty** [comment]
I'm very much in favour of this, it was the original intent to be as close to test-kitchen's UX as made sense, to default to the kitchen UX and only deviate when necessary or for good reason. In reality, molecule 1.x UX is quite far from kitchen and this would be a breaking change for (almost?) every molecule.yml, so I agree that this is worth a major version bump.

And to go along with that we should be more careful than usual about documenting the upgrade/testing/releasing, but with that caveat: 👍

**Comment by tknerr** [comment]
+1, would love to see suites support (as long as there can be still multiple instances per suite, which is atm not supported by TK afaik)

**Comment by retr0h** [comment]
Molecule 2.x config syntax proposal.  We would like to use a similar config to test-kitchen.  However, we likely cannot be 100% compatible _nor_ do we need to be.

Below is more vagrant specific, but we should try and normalize the config across drivers. 

```
---
driver:
  name: vagrant
  network:
    - ip: 192.168.50.4
    - type: dhcp
       auto_config: false
  customize:
    memory: 1024
    cpu: 1

provisioner:
  name: ansible
  flag1: foo
  flag2: bar
  env:
    FOO: bar

platforms:
  - name: ubuntu-14.04
     box: ubuntu/trusty64
  - name: ubuntu-12.04
     box: hashicorp/precise64

suites:
  - name: scenario-1
    run_list:
      playbook.yml
```

How do we represent multiple-instances?  Test kitchen combines the suite and platform to create a set of tests it loops through.

I was thinking we treat platforms as instances.  The number of systems listed in platforms == the number of instances we converge.  We then combine that with the suites, so we can create scenario basted testing.

So this would effectively become.

```
platforms:
  - name: ubuntu-14.04
     box: ubuntu/trusty64
  - name: ubuntu-12.04
     box: hashicorp/precise64

suites:
  - name: scenario-1
    run_list:
      playbook1.yml
  - name: scenario-2
    run_list:
      playbook2.yml
```

1.) Create 2 instances
2.) Converge both instances using the playbook from scenario-1
3.) Perform the tests associated with scenario-1.
4.) Destroy the instances
5.) Start again with scenario-2.

I don't see much value in targeting a particular platform.  Is that really necessary or useful?  How would we represent that in the config.
