### ISSUE TITLE
Download dependencies 

### ISSUE THREAD

**Issue by dj-wasabi** [metacloud/molecule#288]
Hi,

One of my ansible roles has some dependencies on other roles. So I have to execute `ansible-galaxy install -r requirements.yml` before running the `molecule test` the ansible-galaxy command to download the dependencies.

Is it possible to let molecule handle this dependencies downloading?

So if for example we have this in the molecule.yml file:
```
ansible:
  playbook: playbook.yml
  timeout: 30
  requirement: requirements.yml
```
Within the `converge` step it can download the dependencies. If it hasn't a value then this step is ignored.

My 2 cents.
