### ISSUE TITLE
Docker port_bindings does not seem to work 

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#387]
Hi there,

i configured the ports as explained:

```yaml
---
ansible:
  playbook: test.yml

docker:
  containers:
  - name: monitor
    image: debian
    image_version: latest
    port_bindings: 
      1080: 1080,
```

but docker still gives me:

```shell
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS               NAMES
1b8a08ee02b6        molecule_local/debian:latest   "/bin/bash"         10 seconds ago      Up 10 seconds                           monitor
```

What am I doing wrong?

Cheers
