### ISSUE TITLE
systemd run_command

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#389]
Hi Guys,

thanks for the awesome tool, could you pass the run_command to docker (as kitchen does)?

Then it starts with systemd (if i get it install prior to the run) and then i can use systemctl, which helps with the init process. (closer to the live environment)

```yaml
platforms:
  - name: "debian"
    driver_config:
      privileged: true
      run_command: /lib/systemd/systemd
```

Cheers,
Alex
