### ISSUE TITLE
Allow custom Dockerfile

### ISSUE THREAD

**Issue by clabu** [metacloud/molecule#393]
Currently the Dockerfile used to customize the image is hard-coded in `molecule/driver/dockerdriver.py`. Allow the option for a custom Dockerfile. I for example need the image to have a corporate proxy configured or I cannot download packages. I would also like an image with init system working. 

Example config:
```
---
docker:
  containers:
    - name: foo-01
      ansible_groups:
      - group1
      dockerfile: tests/Dockerfile.centos-6
      privileged: True
      port_bindings:
        80: 80
    - name: foo-02
      ansible_groups:
        - group2
      image: ubuntu
      image_version: '14.04'
      registry: testhost:5323
      volume_mounts:
        - '/this/volume:/to/this:rw'
      command: '/bin/sh'
```
