### ISSUE TITLE
Kitchen provision_command

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#422]
Hi Guys,

is there a way, that i can install things previously to running provisioning?

Like in Kitchen:
```yaml
provision_command:
   - apt-get install python-setuptools python-netaddr python-pip  -y
```

Cheers,
Alex

**Comment by kireledan** [comment]
That could be a useful addition. I would think that the playbook being tested would just install these though. Or is this a common need?

**Comment by retr0h** [comment]
Yeah, generally if this is needed it should go in the playbook.  I don't see much use in having molecule manage this.  Lets leverage ansible at what it's good at.

I use this pattern for my alpine linux instances.

```
- hosts: all
  gather_facts: False
  tasks:
    - raw: which python || apk update && apk add python
```

To handle your use case, simply add to your playbook.

```
- hosts: util
  tasks:
    - package: name={{ item }}
      with_items:
        - python-setuptools
        - python-netaddr
        - python-pip
```
