### ISSUE TITLE
Testinfra doesn't pass the sudo option

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#496]
The sudo option does not get passed to testinfra?

```
verifier:
  name: testinfra
  options:
    sudo: True
    v: True
```
