### ISSUE TITLE
Idempotence command does not display the non-idempotent tasks

### ISSUE THREAD

**Issue by rgreinho** [metacloud/molecule#527]
The `molecule idempotence` command does not display the non idempotent tasks anymore. This forces the user to run `molecule converge` an extra time and manually look for the guilty tasks.

```sh
$ molecule --version
1.11.4
```

### Repro steps

```sh
mkdir /tmp/molecule-idempotence
cd /tmp/molecule-idempotence
molecule init
```
Use the following playbook:
```yaml
---
- hosts: all
  pre_tasks:
    - name: Idempotence test
      command: echo "Molecule idempotence check"

```
Then run:
```sh
molecule idempotence
```
Output:
```sh
--> Idempotence test in progress (can take a few minutes) ...
--> Starting Ansible Run ...
Idempotence test failed.
```
