### ISSUE TITLE
[question] Any chance to support docker for mac

### ISSUE THREAD

**Issue by milosgajdos83** [metacloud/molecule#535]
Default provisioner in `molecule` is `Vagrant`, however a lot of developers nowadays use `docker` for Mac, which runs `docker` daemon in a small virtual machine as oppose to more full blown `Vagrant` VM.

Some of our `Ansible` roles  merely spin `docker` containers like this:

```
- name: create nginx proxy container
  docker:
    name: nginx
    image: "nginx"
    pull: always
    state: started
    volumes:
      - "{{ nginx_conf }}:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "{{ nginx_port }}:{{ nginx_port }}"
    restart_policy: always
  tags: ['nginx']
```

I wonder if you have any plans to add support for `docker` for Mac or even better, we could do simply with "local" `Ansible` testing without spinning any extra VMs.

**Comment by retr0h** [comment]
@milosgajdos83 already exists, see the [example](http://molecule.readthedocs.io/en/stable-1.12/driver/index.html#usage).

**Comment by retr0h** [comment]
@milosgajdos83 closing.  Please reopen if we didn't address your question.

**Comment by milosgajdos83** [comment]
Hi, I'm sorry for late update. Unfortunately I was swamped doing some other work.

The example you mentioned in your comment is quite nice indeed, but it does not cover testing of the role that set up containers itself. Let me explain what I mean by that. 

The example you posted shows how you can provision the docker containers **inside which** you can test your roles. This is pretty handy for roles which do not set up containers themselves. Roles that basically do stuff outside the containers like setting up configuration files and installing packages. Some of our Ansible create containers using Ansible `docker` module and the container container set up depends on Ansible role variables -- these variables are different in different environments. Let me give you two examples that will illustrate what I'm saying.

Traditiona Ansible role which does not set up any containers in its task list. That is how we test our zookeeper -- which doesn't run in a container but rather directly on a VM. We can test our `zookeeper` role using the Docker driver that you linked me to like this. Our `molecule.yml` looks like this (it uses Docker driver):

```
---
ansible:
  playbook: playbook.yml

docker:
  containers:
  - name: zk01
    ansible_groups:
      - zk_cluster
    image: centos
    image_version: "7.2.1511"
    privileged: True
    port_bindings:
      2181: 2181
      2888: 2888
      3888: 3888
```

Now, the tests are derived from `playbook.yml` which looks like this;

```
---
- hosts: all
  pre_tasks:
    - name: "Get zk01 IP address"
      local_action: command docker inspect --format {% raw %}'{{ .NetworkSettings.IPAddress }}'{% endraw %} zk01
      register: zk01_ip
      become: false
      changed_when: zk01_ip.rc == 12

  vars:
    zk_hosts:
      - host: "{{ zk01_ip.stdout }}"
        id: 1

  roles:
    - role: ansible-zookeeper
```

This is awesome. `molecule.yml` allows to set up a Docker container inside which `ansible-zookeeper` role is run and tested.

** ANSIBLE ROLE THAT SPINS UP DOCKER CONTAINERS**

Take the **following example of a different Ansible role** whose main tasks look like this `ansible-docker-nginx/tasks/main.yml`:

```
- name: create nginx proxy
  docker:
    name: nginx-proxy
    image: "nginx"
    pull: always
    state: started
    log_driver: syslog
    log_opt:
      tag: docker,{{ '{{' }}.ImageID{{ '}}' }},{{ '{{' }}.ImageName{{ '}}' }},{{ '{{' }}.ID{{ '}}' }}
    volumes:
      - "{{ nginx_conf }}:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "{{ nginx_port }}:{{ nginx_port }}"
    restart_policy: always
  tags: ['nginx-proxy']
```

This is a task defined in `main.yml` of `ansible-docker-nginx` role. We can't test this role unless we spin up a docker in a docker or use `Vagrant` provider. Your suggestion was to look at the Docker **provider**, but we can't use this provider to test the role for different variables like `{{ nginx_conf }}` etc. because the provider does not extrapolate Ansible variables for a particular tested role -- that's done in `playbook.yml` not in `molecule.yml`. 

Our options are : we could generate a few `molecule.yml` files for different configurations and then parameterize the tests but that's the way down the rabbit hole of combinatorial explosion of all possible files. Or we could use `Vagrant` provider, but I find it hard to justify to run another VM on my laptop :-/

What would be awesome is to have something like `Vagrant` driver, but instead of vagrant we would use the Docker on Mac. So our `playbook.yml` to test the `ansible-docker-nginx` role could look like this:

```
---
- hosts: all
  vars:
    nginx_port: 8080
    nginx_conf: "/opt/nginx.conf"
  roles:
    - role: ansible-docker-nginx
```

Boom! This would give us again, same self-contained, test just like in the first `zookeeper` role example at the beginning.
