### ISSUE TITLE
Goss test fail does not fail molecule test

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#559]
Hey!

a failed goss does not seem to change molecule's exit code

#### Here is my test file (tests/test_default.yml):

```yaml
---
- hosts: all
  gather_facts: no
  vars:
    goss:
      package:
        php5.6:
          installed: true
        php5.6-cli:
          installed: true
        php5.6-fpm:
          installed: true
      service:
        php5.6-fpm:
          enabled: true
          running: true

  pre_tasks:

    - name: Copy tests to remote
      copy:
        content: "{{ goss | to_nice_yaml }}"
        dest: "/tmp/goss.yml"

    - name: test goss files
      goss:
        path: "/tmp/goss.yml"
        format: documentation
```

#### Here is the output by travis:

![bildschirmfoto 2016-10-15 um 12 17 15](https://cloud.githubusercontent.com/assets/841856/19409311/7330e00c-92d1-11e6-9c30-fdff961909b7.png)

Do you have any idea why?

I totally love the goss support! Awesome!!!
