### ISSUE TITLE
how do I test role against multiple docker images

### ISSUE THREAD

**Issue by cornelius-keller** [metacloud/molecule#596]
Hi all,

I want to test my roles against multiple ansible versions and multiple target images.
For example I want to test the role using ansible 2.0.2.0,2.1.0.0 and 2.2.0.0 against centos7, ubuntu:14.04 and ubuntu:16.04.

For the first part I found a promising solution using tox and molecule together:

```
[tox]
minversion = 1.8
envlist = py{27}-ansible{20,21,22}
skipsdist = true

[testenv]
passenv = *
deps =
    -rrequirements.txt
    ansible20: ansible==2.0.2.0
    ansible21: ansible==2.1.2.0
    ansible22: ansible==2.2.0.0
commands =
    molecule test
```

For molecule I use the following configuration:

```
---
driver:
  name: docker

molecule:
  ignore_paths:
    - .git
    - .vagrant
    - .molecule
    - .tox

docker:
  containers:
    - name: ubuntu_14_04
      image: ubuntu
      image_version: 14.04
      ansible_groups:
        - group1
    - name: ubuntu_16_04
      image: ubuntu
      image_version: 16.04
      ansible_groups:
        - group1
    - name: docker_python_env_centos
      image: centos
      image_version: latest
      ansible_groups:
        - group1

verifier:
  name: testinfra
```

This works, but it will run the Ubuntu 14.04  Ubuntu 16.04 and centos  image in parallel. This is fine if the role is not doing too heavy stuff, but for some of the roles I want to run the tests sequentially.

As far as I understand for the vagrant provider this is solved by the platform section pointing to different boxes. For the docker provider however I did not find an example on how to do this.

Can anybody give me some hints on this?
Thanks in advance 

Cornelius
