### ISSUE TITLE
 force molecule to user custom inventory file

### ISSUE THREAD

**Issue by qrrock** [metacloud/molecule#598]
is there any workaround to force molecule to user custom inventory file? 
i mean, since one understands how container recreation cycle works also name of containers are known;  

current

    # diapl.testrola1/.molecule/ansible_inventory
    diapl.tesrola1 ansible_connection=docker 

exepected

    # diapl.testrola1/.molecule/ansible_inventory
    diapl.testrola1 ansible_port=221  ansible_host=172.23.0.1  ansible_user=app ansible_connection=ssh  ansible_ssh_private_key_file=/home/....../dockers/sandbox_docker/id_rsa

it might help with this https://github.com/metacloud/molecule/issues/597 and probably more

**Comment by retr0h** [comment]
```
ansible:
  inventory_file: ../other_inventory
```

**Comment by qrrock** [comment]
that's what i thought. but as i noticed molecule replace content in my file during the run, i get confused. so is it a bug or i did something wrong

# molecule.yml
```
ansible:
  user: app
  sudo: false
  config_file: ./molecule_ansible.cfg
  playbook: ./molecule_playbook.yml
  inventory_file: ./molecule_inventory
```

# ./molecule_inventory

before run

    diapl.testowarola1 ansible_port=2121  ansible_host=172.23.0.1  ansible_user=app ansible_connection=ssh  ansible_ssh_private_key_file=/home/app/webapp/im_admins/dockers/sandbox_docker/id_rsa

after run (suddenly during)

    diapl.testowarola1 ansible_connection=docker
