### ISSUE TITLE
Add ability to override box_url for different providers

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#627]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
2.1.1.0
molecule --version
1.8.4 (but newer versions too)
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

It is possible to override the vagrant `box_url` for a specific provider (e.g. virtualbox or vmware_workstation)

# Actual Behaviour (Bug report only)

By reading the docs and looking at the vagrantfile template, it looks like there is no way to override the `box_url`. 

For example this molecule.yml:

```
vagrant:
  platforms:
    - name: ubuntu1604
      box: my/ubuntu1604
      box_url: http://fileserv.acme.com/boxes/virtualbox/my-ubuntu1604.box
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2048
        cpus: 2
    - name: vmware_workstation
      type: vmware_workstation
      options:
        memory: 2048
        cpus: 2
```

The issue is that "http://fileserv.acme.com/boxes/virtualbox/my-ubuntu1604.box" always points to the virtualbox variant. 

So if I `molecule create --provider vmware_workstation` this fails because it downloads the wrong box.

It seems there is no possibility to override the `box_url` for a specific provider, or is there?

**Comment by retr0h** [comment]
> By reading the docs and looking at the vagrantfile template, it looks like there is no way to override the box_url.

Override it by how?  What file would you like to override it from?

**Comment by tknerr** [comment]
e.g. like this in molecule.yml:

```
vagrant:
  platforms:
    - name: ubuntu1604
      box: my/ubuntu1604
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2048
        cpus: 2
      raw_config_args:
        - "override.vm.box_url = 'http://fileserv.acme.com/boxes/virtualbox/my-ubuntu1604.box'"
        - "override.vm.network 'private_network', ip: '192.168.220.16'"
    - name: vmware_workstation
      type: vmware_workstation
      options:
        memory: 2048
        cpus: 2
      raw_config_args:
        - "override.vm.box_url = 'http://fileserv.acme.com/boxes/vmware/my-ubuntu1604.box'"
        - "override.vm.network 'private_network', ip: '192.168.230.16'"
```

Just noticed I had a similar issue where I could not start a VM with the vmware_worksation provider because the virtualbox provider already created a virtual network adapter for that subnet.

Allowing provider scoped `raw_config_args` which would then be insterted straight into the `config.vm.provider ...` block in the vagrantfile would probably the easiest and most generic way to solve this.

See what I mean?

**Comment by tknerr** [comment]
e.g. in the resulting `vagrantfile` this should look similar to this:

```ruby

  config.vm.provider 'virtualbox' do |vb, override|
    vb.cpus = 2
    vb.memory = 2048
    override.vm.box_url = 'http://fileserv.acme.com/boxes/virtualbox/my-ubuntu1604.box'
    override.vm.network 'private_network', ip: '192.168.220.16'
  end

  config.vm.provider 'vmware_workstation' do |vmware, override|
    vmware.cpus = 2
    vmware.memory = 2048
    override.vm.box_url = 'http://fileserv.acme.com/boxes/vmware/my-ubuntu1604.box'
    override.vm.network 'private_network', ip: '192.168.230.16'
  end
```

**Comment by retr0h** [comment]
Wouldn't you just make your `molecule.yml`:

```
vagrant:
  platforms:
    - name: ubuntu1604
      box_url: http://fileserv.acme.com/boxes/vmware/my-ubuntu1604.box
...
```
