### ISSUE TITLE
`molecule dependency` doesn't do anything

### ISSUE THREAD

**Issue by pporada-gl** [metacloud/molecule#634]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.2.0.0
molecule, version 1.16.0
```

- Molecule installation method: pip
- Ansible installation method: yum EPEL

# Desired Behaviour

Looking at the code, `molecule dependency` should run the lines listed under the dependency yml header. I would expect that this happens much like `molecule converge`

```
$ molecule dependency 
--> Downloading dependencies with 'galaxy'...
- extracting greenlancer.ROLE to .molecule/roles/greenlancer.ROLE
- greenlancer.ROLE was installed successfully
--> Starting Ansible Run...
```

# Actual Behaviour (Bug report only)

Nothing happens. I have to destroy my vagrant everytime I made a change to one of my dependencies in the `requirements.yml` file. I would assume that `molecule dependency` should force pull all the dependencies so I don't need to do that.
```
$ molecule  --debug dependency 
$ echo $?
0
$ molecule dependency --debug
Error: no such option: --debug
$ echo $?
2
```

```
---
dependency:
  name: galaxy
  requirements_file: test/requirements.yml
  options:
    force: True

driver:
  name: vagrant

ansible:
  diff: True
  sudo: True
  host_key_checking: False
  playbook: test/playbook.yml

vagrant:
  platforms:
    - name: centos7
      box: centos/7
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 1
  instances:
    - name: centos-7-srv1
```

**Comment by retr0h** [comment]
This subcommand only installs the dependencies if they have not been installed, it does not download every time it is run.  If you look at `.molecule/state.yml` you will see it marks the dependencies as installed.

This role is wired into the test scenarios workflow, so it only ever gets run once per create,converge,destroy cycle (`test`) cycle.

**Comment by retr0h** [comment]
I'm open to changing this behavior.

1. Install dependencies on every invocation of the `dependency ` sub command.
2. Don't re-install dependencies if they are already installed inside the test sequence.

How does that sound?

**Comment by pporada-gl** [comment]
That sounds acceptable to me.

**Comment by elliotweiser** [comment]
@retr0h I would agree with point 1, but only partially agree with point 2.  It sounds as though the ability to pass the `--force` option to `ansible-galaxy install` is not respected because of how molecule handles dependencies. Currently, this portion of the YAML has no meaning.

```yaml
  options:
    force: True
```

If possible, I think it makes more sense to run `dependency` every time during the test sequence and leave it up to the tool/provider in question (in this case, `ansible-galaxy`) to determine whether or not it will go re-download those dependencies if they have already been resolved.

**Comment by retr0h** [comment]
> If possible, I think it makes more sense to run dependency every time during the test sequence and leave it up to the tool/provider in question (in this case, ansible-galaxy) to determine whether or not it will go re-download those dependencies if they have already been resolved.

Thats a good idea.  I would need to look at galaxy further, and verify it works this way.  I remember earlier versions of galaxy would error if already downloaded.

**Comment by retr0h** [comment]
I'm going to close this out and not fix it.  Molecule will only install dependencies one time per test cycle.

Molecule v2 fixes this by executing the dependency manager on each invocation of `dependency`.  However, this is not a high enough issue to warrant a v1 fix.

```
[jodewey:~/git/molecule_2/test/scenarios/dependency] [molecule2-env-2.7.12] driver(+6/-6)+ ± molecule dependency --scenario-name ansible-galaxy
--> Scenario: [ansible-galaxy]
--> Dependency: [galaxy]
    - downloading role 'timezone', owned by yatesr
    - downloading role from https://github.com/yatesr/ansible-timezone/archive/1.0.0.tar.gz
    - extracting timezone to /Users/jodewey/git/molecule_2/test/scenarios/dependency/molecule/ansible-galaxy/.molecule/roles/timezone
    - timezone was installed successfully
Dependency completed successfully.
[jodewey:~/git/molecule_2/test/scenarios/dependency] [molecule2-env-2.7.12] driver(+6/-6)+ ± molecule dependency --scenario-name ansible-galaxy
--> Scenario: [ansible-galaxy]
--> Dependency: [galaxy]
    - downloading role 'timezone', owned by yatesr
    - downloading role from https://github.com/yatesr/ansible-timezone/archive/1.0.0.tar.gz
    - extracting timezone to /Users/jodewey/git/molecule_2/test/scenarios/dependency/molecule/ansible-galaxy/.molecule/roles/timezone
    - timezone was installed successfully
Dependency completed successfully.
```

**Comment by jmartinspt** [comment]
I recently started using the molecule to integrate my project's Ansible functions into the CI/CD process and quickly ran into two problems:
* Duplication of the dependency file, for the use of the molecule (project/requirements.yml) and the role itself (project/meta/requirements.yml)
*  Inability to force the download of roles if they had already been installed previously, being cached in the folder ~/.cache.

After much research and many attempts, I found the following solution:

.env.yml
```yaml
---
ANSIBLE_ROLES_PATH: galaxy_roles
```

.gitignore
```text
(...)
galaxy_roles/
(...)
```

molecule/default/molecule.yml
```yaml
---
dependency:
  name: shell
  command: ansible-galaxy install -r meta/requirements.yml -p galaxy_roles/ --force
driver:
  name: docker
platforms:
  - name: molecule-ubuntu
    image: ubuntu
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
```

This way, just by changing `dependency` to shell and executing the command to install roles to a different folder (always forcing the installation) I can use the same dependency file for the molecule and the role itself. 
So I always have the most up-to-date dependencies and avoid code duplication.

I hope it's useful to someone.
