### ISSUE TITLE
Assign vagrant box to instance

### ISSUE THREAD

**Issue by HanXHX** [metacloud/molecule#791]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.2.1.0
molecule, version 1.22.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I would like to select specific box to a vagrant instance (like docker where you can select your OS!).

Something like:

```yaml
vagrant:  
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 256
        cpus: 1
  platforms:
    - name: wheezy64
      box: debian/wheezy64
    - name: jessie64
      box: debian/jessie64
    - name: stretch64
      box: debian/testing64
  instances:
    - name: vagrant-debian-wheezy
      platform_name: wheezy64
    - name: vagrant-debian-jessie 
      platform_name: jessie64
    - name: vagrant-debian-stretch
      platform_name: stretch64
```
