### ISSUE TITLE
How to disable port forwarding when using default driver and provider

### ISSUE THREAD

**Issue by gzm55** [metacloud/molecule#793]
# Issue Type

- Question

# Desired Behaviour

Now the default `ansible_port` is forwarded from the vm. How to make vagrant using host-only network,
and the `ansible_host` / `ansible_port` is directly from the guest hosts.

**Comment by retr0h** [comment]
I need further information.

**Comment by gzm55** [comment]
now, for each vagrant/virtualbox  instance, the host is always 127.0.0.1,  ssh port is a forwarding port (22->2222 or 22--> 2200, etc), and the network mode of the vm nic is nat.
I want to change the network mode to bridge or host-only, and the generating ansible_host in inventory file is the real ip of the vm nic, and the generating ansible_ports are all 22.

**Comment by retr0h** [comment]
@gzm55 That is not possible.  However, you can assign extra interfaces to your VMs through molecule.yml.  This would bring up a host-only network eth1 on both instances.

```
instances:
  - name: vagrant-test-01
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
  - name: vagrant-test-02
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
```
