### ISSUE TITLE
Test matrix or test steps

### ISSUE THREAD

**Issue by hryamzik** [metacloud/molecule#794]
# Issue Type

- Feature request

That's more a question than a feature request for now. Let's say I'd like to test role with different options, or test both installation and removal:

```yml
- hosts: all
  become: yes
  roles:
    - role: selenium
      selenium_role: hub
      selenium_extra_options: "-maxSession 50 -timeout 90 -browserTimeout 90"
      selenium_version: 3.3.1
      tags: selenium

    - role: selenium
      selenium_role: hub
      selenium_extra_options: "-maxSession 50 -timeout 90 -browserTimeout 90"
      selenium_version: 2.3.0
      tags: selenium
```

This playbook will never be idempotent. But it does make sense to test it.

Another nice approach is to reboot test systems before final idempotent test. That could be done by rebooting systems with a playbook task and then checking for service states but that look a bit overcomplicated.

Any ideas on how to support this?
