### ISSUE TITLE
Is it possible to disable provisioning?

### ISSUE THREAD

**Issue by clabu** [metacloud/molecule#797]
# Issue Type
- Question

# Question
Is it possible to configure Molecule to skip the provisioning and teardown step? For example, I might have bare metal hosts that I want to run the playbook and tests against. I want to be able to give Molecule an inventory with the host IPs and Molecule just runs playbook.yml and the tests.

**Comment by popstas** [comment]
You can skip some default test steps overriding `molecule.test.sequence`, add to `molecule.yml`:
``` yaml
molecule:
  test:
    sequence:
      # - destroy # comment unneeded steps
      - dependency
      - syntax
      # - create
      - converge
      - idempotence
      - verify
```

But as i know, you cannot provision bare metal machine, see #778.
