### ISSUE TITLE
role skipped in travis-ci

### ISSUE THREAD

**Issue by tompscanlan** [metacloud/molecule#803]
I'm stumped :)  I've tried everything I can think of.... starting to think this may be an ansible bug, but checking here first.

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.1.0
(also happens under 2.2.2.0)

molecule --version
molecule, version 1.23.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Running inside the role directory photon, 

## Given molecule.yml
```
---

ansible:
  verbose: True
  playbook: tests/travis-playbook.yml
  raw_env_vars:
    ANSIBLE_ROLES_PATH: .molecule/roles/:.molecule/../roles/:../:../../:../../../
driver:
  name: docker
docker:
  containers:
    - name: ubuntu01
      image: ubuntu
      image_version: latest
      ansible_groups:
        - tests

    - name: photon01
      image: photon
      image_version: latest
      dockerfile: tests/dockerfiles/photon-latest
      privileged: true
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      ansible_groups:
        - tests
```

## Given tests/travis-playbook.yml

```
---
- hosts: tests
  roles:
    - role: photon
```

## Given .travis.yml

```
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
install:
  - pip install ansible==2.2.1.0
  - pip install molecule
  # - pip install required driver (e.g. docker, python-vagrant, shade)
  - pip install docker
  - mkdir tests/roles
  - ln -s ../ tests/roles/photon
script:
  - set -x
  - export MOLECULE_PLAYBOOK=tests/travis-playbook.yml
  - export ANSIBLE_CONFIG=.molecule/ansible.cfg
  - molecule --debug test
```

I would expect molecule to run tests under travis the same way as occurs locally on a mac.

# Actual Behaviour (Bug report only)

molecule test on mac laptop works as expected.

```

PLAYBOOK: travis-playbook.yml **************************************************
PLAY [tests] *******************************************************************
TASK [setup] *******************************************************************
TASK [photon : Skipping non photons] *******************************************
...
TASK [photon : ensure yum is installed] ****************************************
...
PLAY RECAP *********************************************************************
photon01                   : ok=7    changed=4    unreachable=0    failed=0
ubuntu01                   : ok=2    changed=0    unreachable=0    failed=0

--> Idempotence test in progress (can take a few minutes)...
--> Starting Ansible Run...
Idempotence test passed.
--> Executing ansible-lint...
--> Destroying instances...
Stopping container ubuntu01...
Removed container ubuntu01.
Stopping container photon01...
Removed container photon01.
```

Under travis-ci ansible is run, we see setup and then recap with no tasks executed for the role.  travis has the hosts according to a --list-hosts

```
...
TASK [setup] *******************************************************************
ok: [ubuntu01]
ok: [photon01]
PLAY RECAP *********************************************************************
photon01                   : ok=1    changed=0    unreachable=0    failed=0   
ubuntu01                   : ok=1    changed=0    unreachable=0    failed=0   

--> Idempotence test in progress (can take a few minutes)...
--> Starting Ansible Run...
Idempotence test passed.
--> Executing ansible-lint...
--> Destroying instances...
Stopping container ubuntu01...
Removed container ubuntu01.
Stopping container photon01...
Removed container photon01.
```

Full travis run at https://travis-ci.org/tompscanlan/ansible-role-photon/builds/220712290

In travis, `ansible-playbook -i .molecule/ansible_inventory tests/travis-playbook.yml --list-hosts --list-tasks --list-tags`
 returns:

```
playbook: tests/travis-playbook.yml
  play #1 (tests): tests	TAGS: []
    pattern: [u'tests']
    hosts (2):
      ubuntu01
      photon01
    tasks:
      TASK TAGS: []
```

While on mac laptop we get:
```
playbook: tests/travis-playbook.yml

  play #1 (tests): tests	TAGS: []
    pattern: [u'tests']
    hosts (2):
      ubuntu01
      photon01
    tasks:
      photon : Skipping non photons	TAGS: []
      photon : Add photon repository	TAGS: []
      photon : ensure yum is installed	TAGS: []
      photon : add additional packages	TAGS: []
      photon : update systemd to fix network daemon crashes	TAGS: []
      photon : Assure pip installed via easy_install on Photon.	TAGS: []
      photon : Upgrade Virtualenv	TAGS: []
      photon : add insecure registries to docker daemon	TAGS: []
      photon : assure docker group exists	TAGS: []
      photon : assure Docker running and started at boot	TAGS: []
      photon : add docker Group spec in Docker unit file	TAGS: []
      photon : Install docker-py	TAGS: []
      photon : install syslog-ng on host	TAGS: []
      photon : configure syslog-ng.conf	TAGS: []
      photon : tell systemd to forward journal to syslog	TAGS: []
      TASK TAGS: []
```
