### ISSUE TITLE
Converge impossible after a reboot of the instances

### ISSUE THREAD

**Issue by blackillzone** [metacloud/molecule#838]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

```
molecule, version 1.23.3
```

- Molecule installation method: pip
- Ansible installation method: OS package from Ansible repositories

# Actual Behaviour (Bug report only)

It's probably not a molecule bug, but more a Vagrant one. I'm actually trying to deactivate SE Linux in a Centos 7 box, and for idempotence tests, I'm doing a reboot of the instances.

The taskfile:

```yaml
- name: Desactivation of SELinux
  selinux:
    state: disabled
  notify:
     - "selinux desactivated"
```

The handler:

```yaml
- name: Restart server for SELinux (only if status changed)
  shell: sleep 2 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0
  ignore_errors: true
  listen: "selinux disabled"

- name: Wait for server to come back
  local_action: wait_for
  args:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    state: started
    delay: 30
    timeout: 300
  listen: "selinux disabled"
```

With sometime, it works perfectly (reboot, and then reconnection behind, and continue the tests), but more often, the instance becomes unavailable, and I cannot do any more converge on it.
The only way is to destroy it, and converge again.

The instance is really listening (so the wait for come back task is passing), and I can see the ports listening on my computer. But when I trying to directly SSH to it, I have a timeout.

Anyone has the same behavior ? Any clue to restart a host more properly ? I maybe do it the wrong way too.

Still, huge thanks for this awesome tool, that saved me tons of hours of playbooks/roles development. Really nice work :).
