### ISSUE TITLE
IP of a Vagrantbox unreacheable after adding it in the molecule.yml

### ISSUE THREAD

**Issue by blackillzone** [metacloud/molecule#839]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

```
molecule, version 1.23.3
```

- Molecule installation method: pip
- Ansible installation method: OS package from Ansible repositories

# Desired Behaviour

IP directly available in the box, after doing a converge.

# Actual Behaviour (Bug report only)

When I'm adding a specific IP to a CentOS 7 box, I need to login and do a ifup inside, in order to make the interface available. 

```yaml
instances:
    - name: tomcat
      interfaces:
        - network_name: private_network
          type: static
          ip: 192.168.1.10
          auto_config: true
      options:
        append_platform_to_hostname: no
      raw_config_args:
        - "vm.network 'forwarded_port', guest: 8080, host: 8080"
```

It seems to not be related to molecule, and I've found you were posting on the Vagrant project (without replies for the  moment): https://github.com/mitchellh/vagrant/issues/8166

Did you find any workaround for this ? Because it's kinda annoying actually, and broke almost all my plays and tests.

Thanks !
