### ISSUE TITLE
Trailing whitespace in molecule.yml after molecule init

### ISSUE THREAD

**Issue by rndmh3ro** [metacloud/molecule#84]
molecule.yml is the default one created with `molecule init`
```
(molecule)user $  molecule verify
Trailing whitespace found in ./molecule.yml on lines: 100
```
At `# box_version:`
```
  # molecule's --platform option will look for these names
  platforms:
    - name: trusty64
      box: trusty64
      box_url: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
      # Optional item, box_version - support for vagrant versioning
      # box_version: 
```
