### ISSUE TITLE
Allow randomness in instance names or use instance IDs

### ISSUE THREAD

**Issue by berendt** [metacloud/molecule#887]
# Issue Type

- Feature request

# Current Behaviour

At the moment it is possible to specify the used OpenStack instance names in the configuration. The problem is that those names are unique. This way it is not possible to run the same configuration multiple times. In my CI I want to use the same configuration to run in parallel to be able to kickoff multiple jobs in parallel and to run Ansible 2.2 and Ansible 2.3 tests in parallel.

# Desired Behaviour

It should be possible to use one configuration in parallel.

**Comment by retr0h** [comment]
molecule.yml can accept env vars.  Just have your CI system use a wrapper script which can generate a random name and set RANDOM_NAME prior to executing molecule.

```
platforms:
  - name: $RANDOM_NAME
    image: centos:latest
```

**Comment by berendt** [comment]
Ah cool, I was not aware of this feature. I think this should work for my use cased. Will test this today.

**Comment by berendt** [comment]
Tested this with version 1.25 and the OpenStack driver. But the variable is not replaced, I receive $VARNAME in the instance name.

**Comment by retr0h** [comment]
Ah, yeah.  Molecule expands the env vars when the config is parsed.  However, thje Ansible playbook is loading the file off disk.  I have an idea.  Once I land #894 I'll fix this.

**Comment by Lirt** [comment]
I feel like the names should be internally randomized by molecule in first run and remembered (as you already do in file `/tmp/molecule/<ROLE>/<SCENARIO>/ansible_inventory.yml`) to avoid instance name conflicts when working in teams and simultaneously using CIs.

Using non-deterministic IDs is currently unusable, since on each command the instance name is different and you cannot target already created machine.

My workaround for this is using "$HOSTNAME" in the instance name, but this is not 100% bulletproof I guess.

**Comment by decentral1se** [comment]
Think this is related to https://github.com/ansible/molecule/issues/1573 and https://github.com/ansible/molecule/issues/1702.

We need to solve this I think ...

**Comment by Frodox** [comment]
@retr0h what do you mean by

> Just have your CI system use a wrapper script which can generate a random name and set RANDOM_NAME prior to executing molecule.

?
I run molecule as
```
docker run --rm \
    ... \
    molecule \
    molecule test
```
and several platforms as
```
---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: ${RANDOM_NAME}
    image: "Ubuntu 16.04"
    flavor: "d1.c1r1"
  - name: ${RANDOM_NAME}
    image: "Ubuntu 18.04"
    flavor: "d1.c1r1"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

So, where should I inject generation of `RANDOM_NAME`, since ansible-playbook runs it in parallel / lookup envs only once
