### ISSUE TITLE
Docker images for service module

### ISSUE THREAD

**Issue by aliusmiles** [metacloud/molecule#899]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.1.0
molecule, version 2.0.0.0rc12.dev18
```

- Molecule installation method: pip from master
- Ansible installation method: brew

# Desired Behaviour

It's a known pain to make docker container to work properly with systemd services. I've came to the following solution, which seems to work the best:
```
platforms:
  - name: centos7
    image: centos:7
    privileged: true
    command: /usr/lib/systemd/systemd
```
The same is required for _fedora_ and _opensuse_ images.
And on a side note, alpine image fails to start with default command `sleep infinity`, so it requires something like:
```
platforms:
  - name: alpine
    image: alpine
    command: sleep 10000
```

And the feature request is: is it possible to add those examples at least in documentation and maybe in molecule.yml template?
