### ISSUE TITLE
How would one supply additional ansible-lint rules?

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#912]
Hi there,

just a question no issue 👍 

I have written my own ansible-lint rules, i would like to add those to the standard ones.

BTW: How can I buy you a 🍺 ?

Cheers,
Alex

**Comment by retr0h** [comment]
If you able to successfully run `ansible-lint` manually on the command line, and know the proper syntax, you can add that to molecule.yml (speaking about molecule v2 not v1).

```
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      'r': relative/path/to/rules/dir/
```

Execute `molecule --debug lint` if you wish to see the env vars passed and CLI options to `ansible-lint`.
