### ISSUE TITLE
Docker repository molecule_local not found

### ISSUE THREAD

**Issue by Gusymochis** [metacloud/molecule#924]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.1.0
molecule --version
molecule, version 2.0.0.0rc14
```

- Molecule installation method: pip
- Ansible installation method: One of source

# Desired Behaviour

Molecule test should provide the same output as the documentation when running the documented example.

# Actual Behaviour

when running the example from the documentation the following error occurs:
$ molecule --debug test
```
...

failed: [localhost] (item={'image': u'centos:7', 'name': u'instance'}) => {
        "failed": true,
        "invocation": {
            "module_args": {
                "api_version": null,
                "blkio_weight": null,
                "cacert_path": null,
                "capabilities": null,
                "cert_path": null,
                "cleanup": false,
                "command": "sleep infinity",
                "cpu_period": null,
                "cpu_quota": null,
                "cpu_shares": null,
                "cpuset_cpus": null,
                "cpuset_mems": null,
                "debug": false,
                "detach": true,
                "devices": null,
                "dns_opts": null,
                "dns_search_domains": null,
                "dns_servers": null,
                "docker_host": null,
                "entrypoint": null,
                "env": null,
                "env_file": null,
                "etc_hosts": null,
                "exposed_ports": null,
                "filter_logger": false,
                "force_kill": false,
                "groups": null,
                "hostname": "instance",
                "ignore_image": false,
                "image": "molecule_local/centos:7",
                "interactive": false,
                "ipc_mode": null,
                "keep_volumes": true,
                "kernel_memory": null,
                "key_path": null,
                "kill_signal": null,
                "labels": null,
                "links": null,
                "log_driver": "syslog",
                "log_options": null,
                "mac_address": null,
                "memory": "0",
                "memory_reservation": null,
                "memory_swap": null,
                "memory_swappiness": null,
                "name": "instance",
                "network_mode": null,
                "networks": null,
                "oom_killer": null,
                "oom_score_adj": null,
                "paused": false,
                "pid_mode": null,
                "privileged": false,
                "published_ports": null,
                "pull": false,
                "purge_networks": false,
                "read_only": false,
                "recreate": false,
                "restart": false,
                "restart_policy": null,
                "restart_retries": null,
                "security_opts": null,
                "shm_size": null,
                "ssl_version": null,
                "state": "started",
                "stop_signal": null,
                "stop_timeout": null,
                "timeout": null,
                "tls": null,
                "tls_hostname": null,
                "tls_verify": null,
                "trust_image_content": false,
                "tty": false,
                "ulimits": null,
                "user": null,
                "uts": null,
                "volume_driver": null,
                "volumes": null,
                "volumes_from": null
            },
            "module_name": "docker_container"
        },
        "item": {
            "image": "centos:7",
            "name": "instance"
        },
        "msg": "Error pulling image molecule_local/centos:7 - 404 Client Error: Not Found (\"{\"message\":\"repository molecule_local/centos not found: does not exist or no pull access\"}\")"
    }

    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by brandonheller** [comment]
This issue occurred for me today as well, after Docker for Mac crashed, offered to reinstall install, and I accepted.

This root cause is when (for some reason) previously created Docker images are no longer present.

When trying to start up a container in a Molecule-generated create.yml, Docker doesn’t see the tag, so it looks for a repository called molecule_local on docker hub for the Docker image, which yields the confusing error.  

The default create.yml has an optimization to avoid duplicating a (presumably unchanged) docker image when the Dockerfile has not changed, but this optimization misses the case where the created Docker image is not present.

Here's the relevant piece of a create.yml file:
```yml
- name: Build an Ansible compatible image
  docker_image:
    path: "{{ molecule_ephemeral_directory }}"
    name: "molecule_local/{{ item.item.image }}"
    dockerfile: "{{ item.item.dockerfile | default(item.invocation.module_args.dest) }}"
    force: "{{ item.item.force | default(True) }}"
  with_items: "{{ platforms.results }}"
  when: platforms.changed
```
Note the when at the end.

My fix is to generalize the changed_when to catch this case.  Here's the updated create.yml, which also fixes the case where you have two instances with the same distribution name but different versions:

create.yml:
```yml
---
- name: Setup
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_ephemeral_directory: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
    molecule_scenario_directory: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Create Dockerfiles from image names
      template:
        # Original (generated) value:
        # src: "{{ molecule_scenario_directory }}/Dockerfile.j2"
        # For now, just assume the single one we have.
        # A more flexible alternate would be to pass something in {{ item.dockerfile }} and use that to specify
        # the location.
        src: Dockerfile.j2
        dest: "{{ molecule_ephemeral_directory }}/Dockerfile_{{ item.name | regex_replace('[^a-zA-Z0-9_]', '_') }}"
      with_items: "{{ molecule_yml.platforms }}"
      register: platforms

    - name: Discover local Docker images
      docker_image_facts:
        name: "molecule_local/{{ item.item.name }}"
      with_items: "{{ platforms.results }}"
      register: docker_images

    - name: Build an Ansible compatible image
      docker_image:
        path: "{{ molecule_ephemeral_directory }}"
        # Make sure to use item.name here to capture version-specific differences.  For multiple versions of
        # Ubuntu, item.item.image will simply be 'ubuntu'.
        name: "molecule_local/{{ item.item.name }}"
        dockerfile: "{{ item.item.dockerfile | default(item.invocation.module_args.dest) }}"
        force: "{{ item.item.force | default(True) }}"
      with_items: "{{ platforms.results }}"
      # Work around the "Docker repository molecule_local not found" error:
      # https://github.com/metacloud/molecule/issues/924
      # This could occur if you reinstalled Docker and it cleared out the list of images, but the generated Dockerfile
      # templates (from the first task above) had not changed, causing 'platforms.changed' to seem unchanged.
      # The right side of the expression below checks for any single example of a missing image.
      # TODO: only generate new images when they're actually needed, on a per-item basis.
      when: platforms.changed or docker_images.results|map(attribute='images')|select('equalto', [])|list|count >= 0

    - name: Create molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        hostname: "{{ item.name }}"
        image: "molecule_local/{{ item.name }}"
        state: started
        recreate: False
        log_driver: syslog
        command: "{{ item.command | default('sleep infinity') }}"
        privileged: "{{ item.privileged | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
      with_items: "{{ molecule_yml.platforms }}"

```

I really like what Molecule is trying to do and how it works so far.  Hoping to start submitting patches soon.  Thanks!

**Comment by retr0h** [comment]
Yeah, unfortunately with all of my functional tests, I didn't think through this possibility, and hadn't triggered the bug until I removed all of my docker images.

I'll be sure to add a functional test for this situation in the future.

@brandonheller your work-a-round looks like a step in the right direction.

**Comment by brandonheller** [comment]
@retr0h The dockerfile line change came from trying to move as much stuff as possible into a shared directory, so that each role could have a minimum of replicated stuff.   Was able to get it down to one molecule.yml file per role, something like the below, with a top-level shared dir containing a standard shared create.yml, destroy.yml, dockerfile, and others.  Would be great if there were a way to reduce this even further and share everything in it (short of doing a symlink), then override only as necessary (like for a custom dockerfile or playbook that requires vars) - do you know if there's a way?

```yml
---
lint:
  name: yamllint
  options:
    # Oddly, this is relative to where 'molecule test' is executed, not to where this file is defined.
    config-file: "../../.yamllint"
platforms:
  - name: instance-1604
    image: ubuntu
    image_version: "16.04"
  - name: instance-1404
    image: ubuntu
    image_version: "14.04"
provisioner:
  name: ansible
  playbooks:
    setup: ../../../../molecule-shared/create.yml
    teardown: ../../../../molecule-shared/destroy.yml
    converge: ../../../../molecule-shared/playbook-3-dirs-up.yml
``` 

The converge file is an ugly jinja bit but at least removes duplication.
```yml
---
# Playbook slightly modified from the one generated by 'molecule init'.
# This little hack assumes that the rolename is three levels up in the hierarchy from where the molecule.yml file
# is defined.
# This way, each molecule.yml file doesn't need a corresponding playbook.yml file to do the converge step.
# At the same time, you have the flexibility in molecule.yml to override this to run scenarios with multiple
# roles.
- name: Converge
  hosts: all
  roles:
    - role: "{{ lookup('env', 'MOLECULE_FILE') | dirname | dirname | dirname | basename }}"

```
