### ISSUE TITLE
Linting doesn't appear to work

### ISSUE THREAD

**Issue by ticktockhouse** [metacloud/molecule#926]
- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

molecule --version
molecule, version 1.25.0
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

Linting options should be respected

# Actual Behaviour (Bug report only)
molecule.yml:
```
provisioner:     
  name: ansible                
  lint:
    name: ansible-lint         
    enabled: False
    options:                   
      excludes:       
        - /path/roles/nginx/tasks/setup-Ubuntu.yml
        - /path/roles/nginx/tasks/setup-FreeBSD.yml
ansible:                       
  playbook: tests/playbook.yml 
dependency:     
  name: galaxy    
driver:
  name: docker                 
docker:
  containers:                  
    - name: nginx-test              
      image: solita/ubuntu-systemd            
      image_version: 16.04
      privileged: True
      ansible_groups:          
        - group1               
verifier:
  name: testinfra
  options:
    verbose: true
```
Relevant part of molecule --debug test:
```
/home/jerry/.local/bin/ansible-lint tests/playbook.yml --exclude .git --exclude .vagrant --exclude .molecule
```
I need to exclude some files so the test playbook passes the linting check, however the options don't seem to work. Actually, I realised that this was the config for v2, but I can't find any relevant config for v1..
