### ISSUE TITLE
Scenario name seems to be "default"

### ISSUE THREAD

**Issue by ticktockhouse** [metacloud/molecule#927]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
molecule, version 2.0.0.0rc16
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

Create a new scenario with a given name (required by `molecule init`) and have it used correctly

# Actual Behaviour (Bug report only)

When instantiating a molecule env in a pre-existing role using `molecule scenario init`, `--role-name` and `--scenario-name` are required, however if you then run e.g. a `molecule check`, you get the error:
```
ERROR: Scenario 'default' not found.  Exiting.
```
It seems as if "default" is hardcoded somewhere as this is what `molecule.yml` looks like:
```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: new-scenario
verifier:
  name: testinfra
  lint:
    name: flake8
``` 
If I then change the scenario name to "default" in molecule.yml, it works..

Thanks
