### ISSUE TITLE
Problems with systemd inside docker container

### ISSUE THREAD

**Issue by ticktockhouse** [metacloud/molecule#928]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
molecule, version 2.0.0.0rc16
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour

Testing for systemd services inside containers should work

# Actual Behaviour (Bug report only)
In molecule v1.25, it was possible to get round the systemd error:
```
stderr=u'Failed to connect to bus: No such file or directory'
```
by adding:
```
docker:
  containers:
      privileged: True
```
However, this doesn't seem to work in v2 (and there's no corresponding "docker" key. I tried adding:
```
platforms:
  - name: instance
    image: solita/ubuntu-systemd:16.04
    privileged: True
```
...but this doesn't seem to work. As you can see, I'm using a systemd-enabled container. I can confirm that this was working in v1.25 with the "privileged: True" option.

**Comment by retr0h** [comment]
Are you modifying the molecule.yml inside the scenario directory?  As you see I am able to test these types of containers in my [etcd role](https://github.com/retr0h/ansible-etcd/blob/master/molecule/ubuntu/molecule.yml#L8-L14).

**Comment by ticktockhouse** [comment]
Thanks, it was the `command: /sbin/init` that did the trick:
```
platforms:
  - name: instance
    image: solita/ubuntu-systemd:16.04
    privileged: True
    command: /sbin/init
```
Many Thanks
