### ISSUE TITLE
Idempotence test fails during test - no further info available

### ISSUE THREAD

**Issue by ticktockhouse** [metacloud/molecule#931]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
molecule, version 2.0.0.0rc16

```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

Idempotence test should not fail during `molecule test` if it didn't fail during `molecule idempotence`

# Actual Behaviour (Bug report only)

Given the following ansible role snippet, 
```
........
  post_tasks:
    - name: Check for existence of test site (bleedin idempotence) 
      stat: path="{{ test_site_index }}"
      register: test_site_index_file  
    
    - name: Set up test site   
      shell: echo "Hello World" > "{{ test_site_index }}"
      when: not test_site_index_file.stat.exists
          
    - name: Ensure Correct permissions for site root file
      file: path=/var/www/test/index.html mode=0644 owner=www-data group=www-data
      when: test_site_index_file.stat.exists
```

`molecule test` returns:
```
--> Scenario: 'default'
--> Action: 'idempotence'
ERROR: Idempotence test failed because of the following tasks:
* [instance] => Ensure Correct permissions for site root file
```
and `molecule idempotence` returns:
```
--> Scenario: 'default'
--> Action: 'idempotence'
Idempotence completed successfully.
```

Unfortunately, `molecule --debug test` doesn't seem to give any more information about the failure, so not sure whhat's causing this.
