### ISSUE TITLE
Using group_vars in molecule.yml does not work

### ISSUE THREAD

**Issue by dj-wasabi** [metacloud/molecule#939]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3.2.0
  config file = /Users/wdijkerman/git/ansible/access/ansible.cfg
  configured module search path = [u'Library']
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
molecule, version 2.0.2
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

According to the documentation found on http://molecule.readthedocs.io/en/latest/configuration.html#id11, the following is how I should configure molecule to use group_vars: 
```
platforms:
  - name: instance
    image: milcom/centos7-systemd:latest
    groups:
      - group1
    privileged: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      group1:
        user_groups:
         - name: admin
           gid: 1100
        system_users:
         - name: vault
           account: vault
           uid: 1051
         - name: consul
           account: consul
           uid: 1050
        users:
         - name: wdijkerman
           account: wdijkerman
           home: /home/wdijkerman
           state: present
           uid: 1000
           groups:
             - admin
           pub_key: blabla
         - name: jenkins
           account: jenkins
           home: /var/lib/jenkins
           state: present
           uid: 1052
           groups:
             - admin
           pub_key: ssh-rsa blabla
        users_in_group:
         - admin
```
I would expect that 4 lists with data are available in my role and tasks can use it.

# Actual Behaviour (Bug report only)

Executing a `converge` would lead to:
```
--> Action: 'converge'
    
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [instance]
    
    TASK [ansible-access : Creating groups] ****************************************
    
    TASK [ansible-access : Managing System users] **********************************
    
    TASK [ansible-access : Managing System users] **********************************
    
    TASK [ansible-access : Managing users] *****************************************
    
    TASK [ansible-access : Remove password expiration] *****************************
    failed: [instance] (item=wdijkerman) => {"failed": true, "item": "wdijkerman", "msg": "unable to find user wdijkerman in /etc/shadow"}
    failed: [instance] (item=jenkins) => {"failed": true, "item": "jenkins", "msg": "unable to find user jenkins in /etc/shadow"}
    
    PLAY RECAP *********************************************************************
    instance                   : ok=1    changed=0    unreachable=0    failed=1
```
It fails because the `wdijkerman` and the `jenkins` is not created.
