### ISSUE TITLE
Destroy step is not executed if converge playbook failed

### ISSUE THREAD

**Issue by azhurbilo** [metacloud/molecule#945]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version = 2.3.0.0
molecule --version = 2.0.4
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

```
scenario:
  name: test_role_zookeeper
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - destroy
```
Last Destroy step runs all time regardless of result from previous steps.
Must have feature for CI

# Actual Behaviour (Bug report only)

Ansible "converge" playbook failes with output:

molecule --debug test -s test_role_zookeeper

```
    PLAY RECAP *********************************************************************
    test-role-zookeeper-instance-01.molecule : ok=1    changed=0    unreachable=0    failed=1
    test-role-zookeeper-instance-02.molecule : ok=1    changed=0    unreachable=0    failed=1
    test-role-zookeeper-instance-03.molecule : ok=1    changed=0    unreachable=0    failed=1

ERROR:
```

and step "destroy" is not triggered
