### ISSUE TITLE
feature: Add a 'prepare' step as part of creation of VM

### ISSUE THREAD

**Issue by mzsilak** [metacloud/molecule#963]
# Issue Type
- Feature request

# Molecule and Ansible details

```
ansible 2.3.2.0
molecule master
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

The _create_ step of a scenario shall be able to execute tasks on a VM after its creation through a new template file _prepare.yml_. The file shall tasks to prepare the VM for the intended scenario and role.

Minimum content (moved from playbook.yml):
```
- name: Prepare
  hosts: all
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum clean all -y && yum install python-minimal -y)
      become: True
```

The _prepare.yml_ shall only be executed as part of VM creation. If the VM exists already it must not be executed to keep the idempotence of the _converge_ step

# Motivation

The current execution steps always target a fresh installation of a role. The addition of a _prepare_ step allows testing of roles in existing or (manually) modified environments and fits the possibility to create multiple scenarios with molecule.
