### ISSUE TITLE
"Failed to connect to the host via ssh" using Vagrant

### ISSUE THREAD

**Issue by pescobar** [metacloud/molecule#985]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.0.0
molecule, version 2.2.0
Python 2.7.5 in a Centos 7.3 machine
```

- Molecule installation method: pip inside virtualenv
- Ansible installation method: pip inside virtualenv

# Actual Behaviour (Bug report only)

After installing latest ansible and latest molecule using pip I create a test template running `molecule init role -d vagrant -r test_role` and then I do `molecule test` and I get this error:

```
    PLAY [Prepare] *****************************************************************

    TASK [Install python for Ansible] **********************************************
    task path: /data/ansible/test_role/molecule/default/prepare.yml:6
    <instance> ESTABLISH SSH CONNECTION FOR USER: None
    <instance> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/%h-%p-%r -tt instance 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-znzfjuybndcpttjdqqxyxxfupbaxtuzx; test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)'"'"''
    <instance> (255, '', 'ssh: Could not resolve hostname instance: Name or service not known\r\n')
    fatal: [instance]: UNREACHABLE! => {
        "changed": false, 
        "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname instance: Name or service not known\r\n", 
        "unreachable": true
    }
    
    PLAY RECAP *********************************************************************
    instance                   : ok=0    changed=0    unreachable=1    failed=0
```

If I switch to another virtualenv in the same machine with ansible-2.3.1.0 and molecule-2.1.0 `molecule test` works ok . I am using the same role template which I have created with molecule-2.2.0. I only switch from one virtualenv to another virtualenv with different versions of ansible and molecule.

This is the list of python packages installed in the working virtualenv with ansible2.3 and molecule2.1
https://gist.github.com/anonymous/da4648b03fad895cf543d9446d4efc73

This is the list of python packages in the failing virtual environment with ansible2.4 and molecule2.2
https://gist.github.com/1db743bedf162d37689a188b055f407b

**Comment by alainchiasson** [comment]
Same for me : 

```
ansible (2.4.0.0)
ansible-lint (3.4.15)
molecule (2.2.0)
python-vagrant (0.5.15)

Python 2.7.10
```

I'm on OSX.

What I have seen it fails in the `prepare.yml` on the first run of `molecule create`.

`moleucule/default/.molecule/ansible_inventory.yml` file does not get updated on the first run.

```
---
all:
  hosts:
    instance: &id001 {}
ungrouped:
  hosts:
    instance: *id001
  vars: {}
```

The VM is created and running (the centos box is powered off - it is created as a template to clone from)

```
VBoxManage list vms
"centos-7-1-1.x86_64_1507233116613_53174" {c2ec312b-4f65-439a-9cd0-5769b92449c4}
"molecule_instance_1507233126231_72657" {2308344d-0ea1-4edb-ae98-1d9811838cc3}
```

But the second run works fine. The values are updated.

```
---
all:
  hosts:
    instance: &id001
      ansible_host: 127.0.0.1
      ansible_port: '2222'
      ansible_private_key_file: /Users/alain/Documents/dev/recipe/molecule/default/.molecule/.vagrant/machines/instance/virtualbox/private_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: vagrant
      connection: ssh
ungrouped:
  hosts:
    instance: *id001
  vars: {}
```

So everything else works after - it just breaks the test flow .
