### ISSUE TITLE
Unable to query for become sudo passphrase

### ISSUE THREAD

**Issue by msheiny** [metacloud/molecule#992]
# Issue Type

- Feature request - Add an option to molecule to pass a sudo password to ansible

I'm unable to prompt for a become/sudo password because of how molecule is calling ansible. I've been trying to work around it by using an askpass program but that doesn't cache and will prompt me at every task :( 

I gather the next question will be why do I want this feature? Well the more I read about docker security, it seems problematic to have a user configured to be able to run docker commands without credentials -- its essentially the same as giving your user password-less sudo access (http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/).


# Molecule and Ansible details

```
$ molecule --version    
molecule, version 2.2.1   

$ ansible --version     
ansible 2.4.0.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

```
$ molecule --ask-sudo-pass converge -s dev
# insert password prompt here
```

# Current Behaviour

```
╰─$ molecule create                                                                      
--> Test matrix                                     
└── default               
    ├── create            
    └── prepare           
--> Scenario: 'default'   
--> Action: 'create'      
/usr/lib64/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)         
Warning: Password input may be echoed.              

```

## Askpass notes

I'd actually be happy if someone could point me to a GUI askpass solution that would work in this case, the few I can find in my repository designed for openssh to not cache and are prompting for each become task :( I realize that question is totally out of scope of molecule and this ticket but I still feel like it would be great to document in your repo if future folks have this same question.

 Was calling that like so:

molecule.yml:
```yml
provisioner:                                                                                                                                                                                                   
  name: ansible                                                                                                                                                                                                
    config_options:                                                                                                                                                                                              
      defaults:                                                                                                                                                                                                  
        sudo_flags: -A   
```

```bash
$ SUDO_ASKPASS=/usr/libexec/openssh/x11-ssh-askpass molecule converge -s dev
```
